#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ChimeranPowerGenerator

#include "Basic.hpp"

#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ChimeranPowerGenerator.BP_ChimeranPowerGenerator_C
// 0x0020 (0x06E0 - 0x06C0)
class ABP_ChimeranPowerGenerator_C final : public ACrSolarPanel
{
public:
	class UStaticMeshComponent*                   Tiles;                                             // 0x06C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Foundation;                                        // 0x06C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   BuildingMesh;                                      // 0x06D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Root;                                              // 0x06D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void GetBuildingMeshes(class UMeshComponent** MainBody, TArray<class UMeshComponent*>* AdditionalMeshes) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ChimeranPowerGenerator_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ChimeranPowerGenerator_C")
	}
	static class ABP_ChimeranPowerGenerator_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ChimeranPowerGenerator_C>();
	}
};
DUMPER7_ASSERTS_ABP_ChimeranPowerGenerator_C;

SDK_NAMESPACE_END
