#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroneVerticalConnector

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_DroneVerticalConnector.BP_DroneVerticalConnector_C.ExecuteUbergraph_BP_DroneVerticalConnector
// 0x0018 (0x0018 - 0x0000)
struct BP_DroneVerticalConnector_C_ExecuteUbergraph_BP_DroneVerticalConnector final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         K2Node_Event_NewTier;                              // 0x0004(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_Conv_IntToText_ReturnValue;               // 0x0008(0x0010)()
};
DUMPER7_ASSERTS_BP_DroneVerticalConnector_C_ExecuteUbergraph_BP_DroneVerticalConnector;

// Function BP_DroneVerticalConnector.BP_DroneVerticalConnector_C.OnTierSet
// 0x0004 (0x0004 - 0x0000)
struct BP_DroneVerticalConnector_C_OnTierSet final
{
public:
	int32                                         NewTier;                                           // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_DroneVerticalConnector_C_OnTierSet;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
