#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Exploder_Tier3_Prototype_ShellActor

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Exploder_Tier3_Prototype_ShellActor.BP_Exploder_Tier3_Prototype_ShellActor_C
// 0x0048 (0x02F0 - 0x02A8)
class ABP_Exploder_Tier3_Prototype_ShellActor_C final : public AActor
{
public:
	class UStaticMeshComponent*                   StaticMesh3;                                       // 0x02A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh2;                                       // 0x02B0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh1;                                       // 0x02B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   StaticMesh;                                        // 0x02C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Part4;                                             // 0x02C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Part3;                                             // 0x02D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Part2;                                             // 0x02D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Part1;                                             // 0x02E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x02E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void DestroyShellPartClosestToPoint(const struct FVector& Point);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Exploder_Tier3_Prototype_ShellActor_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Exploder_Tier3_Prototype_ShellActor_C")
	}
	static class ABP_Exploder_Tier3_Prototype_ShellActor_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Exploder_Tier3_Prototype_ShellActor_C>();
	}
};
DUMPER7_ASSERTS_ABP_Exploder_Tier3_Prototype_ShellActor_C;

SDK_NAMESPACE_END
