#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_FE2_Powered_Device_Legs

#include "Basic.hpp"

#include "Chimera_structs.hpp"
#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_FE2_Powered_Device_Legs.BP_FE2_Powered_Device_Legs_C
// 0x0058 (0x0718 - 0x06C0)
class ABP_FE2_Powered_Device_Legs_C final : public ACrBuildingActorBase
{
public:
	class UStaticMeshComponent*                   PlacementHelper;                                   // 0x06C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_DronePole_1Rail_Tip;                            // 0x06C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_ControlStationKey_Red;                          // 0x06D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_DronePole_250;                                  // 0x06D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Static;                                            // 0x06E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Meshes;                                            // 0x06E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAuActorPlacementSocketsComponent*      AuActorPlacementSockets;                           // 0x06F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class UMeshComponent*>                 tab_meshes;                                        // 0x06F8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class ABP_Smelter_C*                          Target;                                            // 0x0708(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	ECrBuildingState                              BuildingState;                                     // 0x0710(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void Get_Meshes(class USceneComponent* Static_0, class USceneComponent* Animated, TArray<class UMeshComponent*>* NewParam) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_FE2_Powered_Device_Legs_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_FE2_Powered_Device_Legs_C")
	}
	static class ABP_FE2_Powered_Device_Legs_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_FE2_Powered_Device_Legs_C>();
	}
};
DUMPER7_ASSERTS_ABP_FE2_Powered_Device_Legs_C;

SDK_NAMESPACE_END
