#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Melee_Tier0_Ragdoll_DeathSequenceActor

#include "Basic.hpp"

#include "BP_Melee_Tier0_Ragdoll_DeathSequenceActor_classes.hpp"
#include "BP_Melee_Tier0_Ragdoll_DeathSequenceActor_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Melee_Tier0_Ragdoll_DeathSequenceActor.BP_Melee_Tier0_Ragdoll_DeathSequenceActor_C.ExecuteUbergraph_BP_Melee_Tier0_Ragdoll_DeathSequenceActor
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Melee_Tier0_Ragdoll_DeathSequenceActor_C::ExecuteUbergraph_BP_Melee_Tier0_Ragdoll_DeathSequenceActor(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Melee_Tier0_Ragdoll_DeathSequenceActor_C", "ExecuteUbergraph_BP_Melee_Tier0_Ragdoll_DeathSequenceActor");

	Params::BP_Melee_Tier0_Ragdoll_DeathSequenceActor_C_ExecuteUbergraph_BP_Melee_Tier0_Ragdoll_DeathSequenceActor Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Melee_Tier0_Ragdoll_DeathSequenceActor.BP_Melee_Tier0_Ragdoll_DeathSequenceActor_C.OnDissolveProgressChanged
// (Event, Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   DissolveProgress                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Melee_Tier0_Ragdoll_DeathSequenceActor_C::OnDissolveProgressChanged(float DissolveProgress)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Melee_Tier0_Ragdoll_DeathSequenceActor_C", "OnDissolveProgressChanged");

	Params::BP_Melee_Tier0_Ragdoll_DeathSequenceActor_C_OnDissolveProgressChanged Parms{};

	Parms.DissolveProgress = DissolveProgress;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Melee_Tier0_Ragdoll_DeathSequenceActor.BP_Melee_Tier0_Ragdoll_DeathSequenceActor_C.OnRagdollStart
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Melee_Tier0_Ragdoll_DeathSequenceActor_C::OnRagdollStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Melee_Tier0_Ragdoll_DeathSequenceActor_C", "OnRagdollStart");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
