#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ModularStairsBarrierR_UniqueHelper

#include "Basic.hpp"

#include "BP_PlacementHelperReplicatedModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ModularStairsBarrierR_UniqueHelper.BP_ModularStairsBarrierR_UniqueHelper_C
// 0x0000 (0x0B70 - 0x0B70)
class ABP_ModularStairsBarrierR_UniqueHelper_C final : public ABP_PlacementHelperReplicatedModule_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ModularStairsBarrierR_UniqueHelper_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ModularStairsBarrierR_UniqueHelper_C")
	}
	static class ABP_ModularStairsBarrierR_UniqueHelper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ModularStairsBarrierR_UniqueHelper_C>();
	}
};
DUMPER7_ASSERTS_ABP_ModularStairsBarrierR_UniqueHelper_C;

SDK_NAMESPACE_END
