#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlacementHelperConnector

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PlacementHelperConnector.BP_PlacementHelperConnector_C
// 0x0050 (0x0B20 - 0x0AD0)
class ABP_PlacementHelperConnector_C final : public ACrAPHelperActorCustomSpline
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AD0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Sphere;                                            // 0x0AD8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UArrowComponent*                        Arrow;                                             // 0x0AE0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class USplineMeshComponent*>           SplineMeshes;                                      // 0x0AE8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class UStaticMeshComponent*>           Steps;                                             // 0x0AF8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	bool                                          IsNarrow;                                          // 0x0B08(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_B09[0x7];                                      // 0x0B09(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Stairs_Angle;                                      // 0x0B10(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Ladder_Angle;                                      // 0x0B18(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_PlacementHelperConnector(int32 EntryPoint);
	double GetRampAngle();
	bool IsLadder();
	bool IsRamp();
	void OnSplinePointAdded(int32 PointIndex);
	void OnSplinePointRemoved(int32 PointIndex);
	void ReceiveTick(float DeltaSeconds);
	void RemoveSteps(int32 Amount);
	void SetMeshColor(const struct FLinearColor& Color);
	void SetSplineSegment(class USplineMeshComponent* SplineMeshComponent, int32 FirstPointIndex, int32 SecondPointIndex);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlacementHelperConnector_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlacementHelperConnector_C")
	}
	static class ABP_PlacementHelperConnector_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlacementHelperConnector_C>();
	}
};
DUMPER7_ASSERTS_ABP_PlacementHelperConnector_C;

SDK_NAMESPACE_END
