#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlacementHelperReplicatedCustom_Pillar

#include "Basic.hpp"

#include "BP_PlacementHelperReplicatedCustom_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PlacementHelperReplicatedCustom_Pillar.BP_PlacementHelperReplicatedCustom_Pillar_C
// 0x0000 (0x09B0 - 0x09B0)
class ABP_PlacementHelperReplicatedCustom_Pillar_C final : public ABP_PlacementHelperReplicatedCustom_C
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlacementHelperReplicatedCustom_Pillar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlacementHelperReplicatedCustom_Pillar_C")
	}
	static class ABP_PlacementHelperReplicatedCustom_Pillar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlacementHelperReplicatedCustom_Pillar_C>();
	}
};
DUMPER7_ASSERTS_ABP_PlacementHelperReplicatedCustom_Pillar_C;

SDK_NAMESPACE_END
