#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ranged_Tier1_Reskin_A_Actor_Character

#include "Basic.hpp"

#include "BP_Ranged_Tier1_Reskin_A_Actor_Character_classes.hpp"
#include "BP_Ranged_Tier1_Reskin_A_Actor_Character_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Ranged_Tier1_Reskin_A_Actor_Character.BP_Ranged_Tier1_Reskin_A_Actor_Character_C.ExecuteUbergraph_BP_Ranged_Tier1_Reskin_A_Actor_Character
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ranged_Tier1_Reskin_A_Actor_Character_C::ExecuteUbergraph_BP_Ranged_Tier1_Reskin_A_Actor_Character(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ranged_Tier1_Reskin_A_Actor_Character_C", "ExecuteUbergraph_BP_Ranged_Tier1_Reskin_A_Actor_Character");

	Params::BP_Ranged_Tier1_Reskin_A_Actor_Character_C_ExecuteUbergraph_BP_Ranged_Tier1_Reskin_A_Actor_Character Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ranged_Tier1_Reskin_A_Actor_Character.BP_Ranged_Tier1_Reskin_A_Actor_Character_C.GetNiagaraEyeSystem
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UNiagaraComponent**               NewParam                                               (Parm, OutParm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)

void ABP_Ranged_Tier1_Reskin_A_Actor_Character_C::GetNiagaraEyeSystem(class UNiagaraComponent** NewParam)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ranged_Tier1_Reskin_A_Actor_Character_C", "GetNiagaraEyeSystem");

	Params::BP_Ranged_Tier1_Reskin_A_Actor_Character_C_GetNiagaraEyeSystem Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function BP_Ranged_Tier1_Reskin_A_Actor_Character.BP_Ranged_Tier1_Reskin_A_Actor_Character_C.OnAiDied
// (Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FHitResult&                HitResult                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// const struct FGameplayTag&              KillingDamageTag                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void ABP_Ranged_Tier1_Reskin_A_Actor_Character_C::OnAiDied(const struct FHitResult& HitResult, const struct FGameplayTag& KillingDamageTag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ranged_Tier1_Reskin_A_Actor_Character_C", "OnAiDied");

	Params::BP_Ranged_Tier1_Reskin_A_Actor_Character_C_OnAiDied Parms{};

	Parms.HitResult = std::move(HitResult);
	Parms.KillingDamageTag = std::move(KillingDamageTag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Ranged_Tier1_Reskin_A_Actor_Character.BP_Ranged_Tier1_Reskin_A_Actor_Character_C.OnEnterActorPool
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Ranged_Tier1_Reskin_A_Actor_Character_C::OnEnterActorPool()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ranged_Tier1_Reskin_A_Actor_Character_C", "OnEnterActorPool");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ranged_Tier1_Reskin_A_Actor_Character.BP_Ranged_Tier1_Reskin_A_Actor_Character_C.OnExitActorPool
// (Public, BlueprintCallable, BlueprintEvent)

void ABP_Ranged_Tier1_Reskin_A_Actor_Character_C::OnExitActorPool()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ranged_Tier1_Reskin_A_Actor_Character_C", "OnExitActorPool");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ranged_Tier1_Reskin_A_Actor_Character.BP_Ranged_Tier1_Reskin_A_Actor_Character_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_Ranged_Tier1_Reskin_A_Actor_Character_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ranged_Tier1_Reskin_A_Actor_Character_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Ranged_Tier1_Reskin_A_Actor_Character.BP_Ranged_Tier1_Reskin_A_Actor_Character_C.OnMeshVisibilityUpdated
// (Event, Public, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// bool                                    bIsMeshHidden                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Ranged_Tier1_Reskin_A_Actor_Character_C::OnMeshVisibilityUpdated(bool bIsMeshHidden) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Ranged_Tier1_Reskin_A_Actor_Character_C", "OnMeshVisibilityUpdated");

	Params::BP_Ranged_Tier1_Reskin_A_Actor_Character_C_OnMeshVisibilityUpdated Parms{};

	Parms.bIsMeshHidden = bIsMeshHidden;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
