#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ranged_Tier2_LOD0_Character

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_BaseAI_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Ranged_Tier2_LOD0_Character.BP_Ranged_Tier2_LOD0_Character_C
// 0x0020 (0x0D20 - 0x0D00)
class ABP_Ranged_Tier2_LOD0_Character_C final : public ABP_BaseAI_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Ranged_Tier2_LOD0_Character_C;   // 0x0D00(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      NiagaraEyes;                                       // 0x0D08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      SpitDrip;                                          // 0x0D10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                        InjuryPoseAlpha;                                   // 0x0D18(0x0008)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Ranged_Tier2_LOD0_Character(int32 EntryPoint);
	void GetNiagaraEyeSystem(class UNiagaraComponent** NewParam);
	void OnAiDied(const struct FHitResult& HitResult, const struct FGameplayTag& KillingDamageTag);
	void OnDamage(class AActor* Actor, const struct FHitResult& HitResult, float InDamage);
	void OnEnterActorPool();
	void OnExitActorPool();
	void OnPrepareForGame();
	void OnRep_InjuryPoseAlpha();
	void SetIsAggroEyeColor(bool NewIsAggro);
	void UserConstructionScript();

	void OnMeshVisibilityUpdated(bool bIsMeshHidden) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Ranged_Tier2_LOD0_Character_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Ranged_Tier2_LOD0_Character_C")
	}
	static class ABP_Ranged_Tier2_LOD0_Character_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Ranged_Tier2_LOD0_Character_C>();
	}
};
DUMPER7_ASSERTS_ABP_Ranged_Tier2_LOD0_Character_C;

}

