#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ranged_Tier2_Ragdoll_DeathSequenceActor

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BP_Ranged_Tier2_Ragdoll_DeathSequenceActor.BP_Ranged_Tier2_Ragdoll_DeathSequenceActor_C.ExecuteUbergraph_BP_Ranged_Tier2_Ragdoll_DeathSequenceActor
// 0x00C0 (0x00C0 - 0x0000)
struct BP_Ranged_Tier2_Ragdoll_DeathSequenceActor_C_ExecuteUbergraph_BP_Ranged_Tier2_Ragdoll_DeathSequenceActor final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      CallFunc_SpawnSystemAttached_ReturnValue;          // 0x0008(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_Event_DissolveProgress;                     // 0x0010(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_DoubleDouble_ReturnValue;    // 0x0014(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_15[0x3];                                       // 0x0015(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_K2_GetActorLocation_ReturnValue;          // 0x0018(0x0018)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FFXSystemSpawnParameters               K2Node_MakeStruct_FXSystemSpawnParameters;         // 0x0030(0x0070)(NoDestructor, ContainsInstancedReference)
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocationWithParams_ReturnValue; // 0x00A0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Not_PreBool_ReturnValue;                  // 0x00A8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x00A9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AA[0x6];                                       // 0x00AA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UAudioComponent*                        CallFunc_SpawnSoundAttached_ReturnValue;           // 0x00B0(0x0008)(ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	double                                        CallFunc_GreaterEqual_DoubleDouble_A_ImplicitCast; // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Ranged_Tier2_Ragdoll_DeathSequenceActor_C_ExecuteUbergraph_BP_Ranged_Tier2_Ragdoll_DeathSequenceActor;

// Function BP_Ranged_Tier2_Ragdoll_DeathSequenceActor.BP_Ranged_Tier2_Ragdoll_DeathSequenceActor_C.OnDissolveProgressChanged
// 0x0004 (0x0004 - 0x0000)
struct BP_Ranged_Tier2_Ragdoll_DeathSequenceActor_C_OnDissolveProgressChanged final
{
public:
	float                                         DissolveProgress;                                  // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Ranged_Tier2_Ragdoll_DeathSequenceActor_C_OnDissolveProgressChanged;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
