#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTT_Exploder_Tier3_Prototype_HideCysts

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BTT_Exploder_Tier3_Prototype_HideCysts.BTT_Exploder_Tier3_Prototype_HideCysts_C
// 0x0010 (0x00B8 - 0x00A8)
class UBTT_Exploder_Tier3_Prototype_HideCysts_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ABP_Exploder_Tier3_Prototype_Actor_Character_C* Character;                                 // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BTT_Exploder_Tier3_Prototype_HideCysts(int32 EntryPoint);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTT_Exploder_Tier3_Prototype_HideCysts_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTT_Exploder_Tier3_Prototype_HideCysts_C")
	}
	static class UBTT_Exploder_Tier3_Prototype_HideCysts_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTT_Exploder_Tier3_Prototype_HideCysts_C>();
	}
};
DUMPER7_ASSERTS_UBTT_Exploder_Tier3_Prototype_HideCysts_C;

SDK_NAMESPACE_END
