#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTT_AddToInt

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_structs.hpp"
#include "AIModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BTT_AddToInt.BTT_AddToInt_C
// 0x0038 (0x00E0 - 0x00A8)
class UBTT_AddToInt_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FBlackboardKeySelector                 IntBBKey;                                          // 0x00B0(0x0028)(Edit, BlueprintVisible)
	int32                                         Val;                                               // 0x00D8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BTT_AddToInt(int32 EntryPoint);
	void ReceiveExecuteAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTT_AddToInt_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTT_AddToInt_C")
	}
	static class UBTT_AddToInt_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTT_AddToInt_C>();
	}
};
DUMPER7_ASSERTS_UBTT_AddToInt_C;

SDK_NAMESPACE_END
