#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CrafterItemContainer

#include "Basic.hpp"

#include "WBP_CrafterItemContainer_classes.hpp"
#include "WBP_CrafterItemContainer_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_CrafterItemContainer.WBP_CrafterItemContainer_C.SetAllSlotsEmptyBackground
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_CrafterItemContainer_C::SetAllSlotsEmptyBackground()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CrafterItemContainer_C", "SetAllSlotsEmptyBackground");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
