#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_BuildingTabsLine

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_BuildingTabsLine.WBP_BuildingTabsLine_C.SetTitle
// 0x0010 (0x0010 - 0x0000)
struct WBP_BuildingTabsLine_C_SetTitle final
{
public:
	class FText                                   InTitle;                                           // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_BuildingTabsLine_C_SetTitle;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
