#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_InventorySplitWindow

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ChimeraUI_classes.hpp"
#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_InventorySplitWindow.WBP_InventorySplitWindow_C
// 0x03D8 (0x0840 - 0x0468)
class UWBP_InventorySplitWindow_C final : public UCrUW_InventorySplitWindow
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0468(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCommonTextBlock*                       ItemNumberStateSlash;                              // 0x0470(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       ItemNumberState;                                   // 0x0478(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       ItemNumberMax;                                     // 0x0480(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWBP_HeaderLine_C*                      ItemInfoWidget;                                    // 0x0488(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_346;                                         // 0x0490(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonBorder*                          Frame;                                             // 0x0498(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FButtonStyle                           ConfirmButtonStyle;                                // 0x04A0(0x0390)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FDataTableRowHandle                    ConfirmRowHandle;                                  // 0x0830(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	void Construct();
	class UWidget* DoCustomNavigation(EUINavigation Navigation_0);
	void ExecuteUbergraph_WBP_InventorySplitWindow(int32 EntryPoint);
	void SetColors(const struct FLinearColor& NormalOrangeColor, const struct FLinearColor& OrangeHighlightColor, const struct FLinearColor& NormalColor);
	void SetupWidget(const class FText& ItemName);
	void UpdateAmountText(int32 Amount);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_InventorySplitWindow_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_InventorySplitWindow_C")
	}
	static class UWBP_InventorySplitWindow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_InventorySplitWindow_C>();
	}
};
DUMPER7_ASSERTS_UWBP_InventorySplitWindow_C;

SDK_NAMESPACE_END
