#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_CraftingBottomPanel

#include "Basic.hpp"

#include "WBP_CraftingBottomPanel_classes.hpp"
#include "WBP_CraftingBottomPanel_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_CraftingBottomPanel.WBP_CraftingBottomPanel_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_CraftingBottomPanel_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CraftingBottomPanel_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_CraftingBottomPanel.WBP_CraftingBottomPanel_C.ExecuteUbergraph_WBP_CraftingBottomPanel
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_CraftingBottomPanel_C::ExecuteUbergraph_WBP_CraftingBottomPanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CraftingBottomPanel_C", "ExecuteUbergraph_WBP_CraftingBottomPanel");

	Params::WBP_CraftingBottomPanel_C_ExecuteUbergraph_WBP_CraftingBottomPanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_CraftingBottomPanel.WBP_CraftingBottomPanel_C.SetEmptyOutItem
// (Event, Protected, BlueprintEvent)

void UWBP_CraftingBottomPanel_C::SetEmptyOutItem()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_CraftingBottomPanel_C", "SetEmptyOutItem");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
