#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_ContinueButton

#include "Basic.hpp"

#include "SlateCore_structs.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function WBP_ContinueButton.WBP_ContinueButton_C.SetTimestamp
// 0x0020 (0x0020 - 0x0000)
struct WBP_ContinueButton_C_SetTimestamp final
{
public:
	class FText                                   InText;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   SessionName;                                       // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm)
};
DUMPER7_ASSERTS_WBP_ContinueButton_C_SetTimestamp;

// Function WBP_ContinueButton.WBP_ContinueButton_C.SetSelected
// 0x0001 (0x0001 - 0x0000)
struct WBP_ContinueButton_C_SetSelected final
{
public:
	bool                                          Selected_SetSelected;                              // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ContinueButton_C_SetSelected;

// Function WBP_ContinueButton.WBP_ContinueButton_C.SetHighlight
// 0x0001 (0x0001 - 0x0000)
struct WBP_ContinueButton_C_SetHighlight final
{
public:
	bool                                          Highlight_SetHighlight;                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ContinueButton_C_SetHighlight;

// Function WBP_ContinueButton.WBP_ContinueButton_C.ExecuteUbergraph_WBP_ContinueButton
// 0x00C0 (0x00C0 - 0x0000)
struct WBP_ContinueButton_C_ExecuteUbergraph_WBP_ContinueButton final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	const class UCrCommonUIColorsDevSettings*     CallFunc_GetSettings_ReturnValue;                  // 0x0008(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor;                      // 0x0010(0x0014)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_1;                    // 0x0024(0x0014)()
	const class UCrCommonUIColorsDevSettings*     CallFunc_GetSettings_ReturnValue_1;                // 0x0038(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	const class UCrCommonUIColorsDevSettings*     CallFunc_GetSettings_ReturnValue_2;                // 0x0040(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_2;                    // 0x0048(0x0014)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_3;                    // 0x005C(0x0014)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_4;                    // 0x0070(0x0014)()
	bool                                          K2Node_Event_Highlight;                            // 0x0084(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_85[0x3];                                       // 0x0085(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	const class UCrCommonUIColorsDevSettings*     CallFunc_GetSettings_ReturnValue_3;                // 0x0088(0x0008)(ConstParm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_5;                    // 0x0090(0x0014)()
	struct FSlateColor                            K2Node_MakeStruct_SlateColor_6;                    // 0x00A4(0x0014)()
	bool                                          K2Node_Event_Selected;                             // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_WBP_ContinueButton_C_ExecuteUbergraph_WBP_ContinueButton;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
