#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_MapMenuAbandonedBaseArea

#include "Basic.hpp"

#include "ChimeraUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_MapMenuAbandonedBaseArea.WBP_MapMenuAbandonedBaseArea_C
// 0x0010 (0x03B0 - 0x03A0)
class UWBP_MapMenuAbandonedBaseArea_C final : public UCrUW_MapMenuAbandonedBaseArea
{
public:
	class UImage*                                 Image_1;                                           // 0x03A0(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image;                                             // 0x03A8(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_MapMenuAbandonedBaseArea_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_MapMenuAbandonedBaseArea_C")
	}
	static class UWBP_MapMenuAbandonedBaseArea_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_MapMenuAbandonedBaseArea_C>();
	}
};
DUMPER7_ASSERTS_UWBP_MapMenuAbandonedBaseArea_C;

SDK_NAMESPACE_END
