#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_QuickActionsContextMenu

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ChimeraUI_structs.hpp"
#include "ChimeraUI_classes.hpp"


SDK_NAMESPACE_START

// WidgetBlueprintGeneratedClass WBP_QuickActionsContextMenu.WBP_QuickActionsContextMenu_C
// 0x0020 (0x0458 - 0x0438)
class UWBP_QuickActionsContextMenu_C final : public UCrUW_QuickActionsMenu
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0438(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_719;                                         // 0x0440(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FDataTableRowHandle                    DefaultConfirmHandle;                              // 0x0448(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor)

public:
	class UCrUW_ActionButton* AddAction(ECrUIInputActionType InAction);
	void ClearMenu();
	void Construct();
	void ExecuteUbergraph_WBP_QuickActionsContextMenu(int32 EntryPoint);
	void SetUsableWidget(bool InUsable);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("WBP_QuickActionsContextMenu_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"WBP_QuickActionsContextMenu_C")
	}
	static class UWBP_QuickActionsContextMenu_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWBP_QuickActionsContextMenu_C>();
	}
};
DUMPER7_ASSERTS_UWBP_QuickActionsContextMenu_C;

SDK_NAMESPACE_END
