#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AuActorPlacement

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "DeveloperSettings_classes.hpp"
#include "PhysicsCore_structs.hpp"
#include "AuActorPlacement_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "MassRepresentation_classes.hpp"
#include "MassEntity_classes.hpp"


SDK_NAMESPACE_START

// Class AuActorPlacement.AuCustomPlacementMethod
// 0x0000 (0x0030 - 0x0030)
class UAuCustomPlacementMethod : public UDataAsset
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuCustomPlacementMethod")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuCustomPlacementMethod")
	}
	static class UAuCustomPlacementMethod* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuCustomPlacementMethod>();
	}
};
DUMPER7_ASSERTS_UAuCustomPlacementMethod;

// Class AuActorPlacement.AuActorPlacementData
// 0x01C0 (0x01F0 - 0x0030)
class UAuActorPlacementData : public UDataAsset
{
public:
	TSubclassOf<class AAuAPHelperActor>           HelperActorClass;                                  // 0x0030(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TSoftClassPtr<class UClass>                   ActorClass;                                        // 0x0038(0x0028)(Edit, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	int32                                         MaxMultiConfirmPoints;                             // 0x0060(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	EAuAPlacementPointsRespectingSurface          PointsRespectingSurfaceMode;                       // 0x0064(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_65[0x3];                                       // 0x0065(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         RangeOfPointsRespectingSurface;                    // 0x0068(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_6C[0x4];                                       // 0x006C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UStaticMesh*                            HelperActorCustomMesh;                             // 0x0070(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected, TObjectPtr)
	bool                                          bRepeatedPlacement;                                // 0x0078(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_79[0x7];                                       // 0x0079(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class FString>                         MeshComponentsToShow;                              // 0x0080(0x0010)(Edit, ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	TArray<class FString>                         MeshComponentsToAlwaysShow;                        // 0x0090(0x0010)(Edit, ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	float                                         MinPlacementDistance;                              // 0x00A0(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         MaxPlacementDistance;                              // 0x00A4(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         DroneMinPlacementDistance;                         // 0x00A8(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         DroneMaxPlacementDistance;                         // 0x00AC(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	class UAuCustomPlacementMethod*               CustomPlacementMethod;                             // 0x00B0(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected, TObjectPtr)
	class UAuActorPlacingConditionsData*          PlacementConditions;                               // 0x00B8(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected, TObjectPtr)
	bool                                          bCanBePlacedOnOil;                                 // 0x00C0(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bCanBePlacedOnTerrain;                             // 0x00C1(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bHasToBePlacedOnTerrain;                           // 0x00C2(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bSnapToHitNormal;                                  // 0x00C3(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bSnapToSocketNormal;                               // 0x00C4(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_C5[0x3];                                       // 0x00C5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<TSubclassOf<class AActor>>             MustHitActors;                                     // 0x00C8(0x0010)(Edit, ZeroConstructor, Protected, UObjectWrapper, NativeAccessSpecifierProtected)
	struct FAuAPSocketParams                      Socket;                                            // 0x00D8(0x0040)(Edit, Protected, NativeAccessSpecifierProtected)
	bool                                          AllSocketsShouldBeSnapped;                         // 0x0118(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAuAPMassSpawnedEntityType             EntityType;                                        // 0x0120(0x0038)(Edit, Protected, NativeAccessSpecifierProtected)
	class UAuActorPlacementData*                  TilesData;                                         // 0x0158(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected, TObjectPtr)
	class UAuActorPlacementData*                  FoundationData;                                    // 0x0160(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected, TObjectPtr)
	float                                         FoundationYaw;                                     // 0x0168(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bForceDirectPlacementTrace;                        // 0x016C(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_16D[0x3];                                      // 0x016D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	ECrBuildingID                                 BuildingID;                                        // 0x0170(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	ECrBuildingID                                 AdditionalHelperBuildingID;                        // 0x0174(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          IsExtractor;                                       // 0x0178(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          CanSnapToActor;                                    // 0x0179(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          CanRotateSnapToActor;                              // 0x017A(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          UseGrid;                                           // 0x017B(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          ForceAllignToTerrain;                              // 0x017C(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          CanBlockZLevel;                                    // 0x017D(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          UseLowCollisionRestriction;                        // 0x017E(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          PlacementHitIgnoreBuildings;                       // 0x017F(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          UseBuildingCamera;                                 // 0x0180(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          CanSetMainMeshZLocation;                           // 0x0181(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_182[0x2];                                      // 0x0182(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MaxMainMeshZLocationShift;                         // 0x0184(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         MinMainMeshZLocationShift;                         // 0x0188(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_18C[0x4];                                      // 0x018C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAuActorPlacementData*                  FoundationHelperVariant;                           // 0x0190(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected, TObjectPtr)
	class UAuActorPlacementData*                  ZOffsetVariantUp;                                  // 0x0198(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected, TObjectPtr)
	class UAuActorPlacementData*                  ZOffsetVariantDown;                                // 0x01A0(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected, TObjectPtr)
	class UAuActorPlacementData*                  AdditionalHelper;                                  // 0x01A8(0x0008)(Edit, ZeroConstructor, NoDestructor, Protected, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierProtected, TObjectPtr)
	bool                                          RequireHabitat;                                    // 0x01B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          RequiresBeingInsideHabitat;                        // 0x01B1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          SplineBased;                                       // 0x01B2(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          CheckBaseCoreArea;                                 // 0x01B3(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          CheckOutsideBaseCoreArea;                          // 0x01B4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	ECrDirection                                  StartHelperDirection;                              // 0x01B5(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1B6[0x2];                                      // 0x01B6(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   AdditionalButtonText;                              // 0x01B8(0x0010)(Edit, BlueprintVisible, Protected, NativeAccessSpecifierProtected)
	bool                                          UsesConnectors;                                    // 0x01C8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          ShowConstrucionHudStability;                       // 0x01C9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          CanRotateInSnapSocket;                             // 0x01CA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          CheckZAxisTraceCollision;                          // 0x01CB(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          RequirePlatformConnecting;                         // 0x01CC(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          StabilityPlatformsHiddenInGame;                    // 0x01CD(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          CanCopyBuilding;                                   // 0x01CE(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1CF[0x1];                                      // 0x01CF(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         SplineHelperZOffset;                               // 0x01D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	float                                         MaxSplineAngle;                                    // 0x01D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	TArray<class FName>                           IgnoredCollisonProfileNames;                       // 0x01D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, Protected, NativeAccessSpecifierProtected)
	bool                                          VerticalDynamic;                                   // 0x01E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bSecondaryRotationEnabled;                         // 0x01E9(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	bool                                          bDoubleConfirmPlacement;                           // 0x01EA(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_1EB[0x5];                                      // 0x01EB(0x0005)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	class AActor* GetActorDefaultObject() const;
	class FName GetBuildingUniqueName() const;

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuActorPlacementData")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuActorPlacementData")
	}
	static class UAuActorPlacementData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuActorPlacementData>();
	}
};
DUMPER7_ASSERTS_UAuActorPlacementData;

// Class AuActorPlacement.AuActorPlacementDeveloperSettings
// 0x0198 (0x01D0 - 0x0038)
class UAuActorPlacementDeveloperSettings final : public UDeveloperSettings
{
public:
	ECollisionChannel                             BuildingTraceChannel;                              // 0x0038(0x0001)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x3];                                       // 0x0039(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         BuildingTraceMaxDistance;                          // 0x003C(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BuildingTraceMinDistance;                          // 0x0040(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InstaRotationAngle;                                // 0x0044(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         InstaOffsetValue;                                  // 0x0048(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MouseToTriggerNormalRotation;                      // 0x004C(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MouseToTriggerSnappedRotation;                     // 0x0050(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_54[0x4];                                       // 0x0054(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 FoundationSocketTag;                               // 0x0058(0x0010)(Edit, ZeroConstructor, Config, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 DrillBeamTag;                                      // 0x0068(0x0010)(Edit, ZeroConstructor, Config, DisableEditOnInstance, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	EPhysicalSurface                              GoldPanelSurfaceType;                              // 0x0078(0x0001)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_79[0x3];                                       // 0x0079(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         MoveSpeed;                                         // 0x007C(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         RotationSpeed;                                     // 0x0080(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MinPitchDown;                                      // 0x0084(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxPitchDown;                                      // 0x0088(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MinPitchTop;                                       // 0x008C(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxPitchTop;                                       // 0x0090(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          DrawDebugPlacementInfo;                            // 0x0094(0x0001)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_95[0x3];                                       // 0x0095(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         GridSizeXY;                                        // 0x0098(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         GridSizeZ;                                         // 0x009C(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BuildingDroneSphereRadius;                         // 0x00A0(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BuildingDroneSpeedPerSec;                          // 0x00A4(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BuildingDroneMaxRadius;                            // 0x00A8(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BuildingDroneWarningRadius;                        // 0x00AC(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BuildingDroneMaxHeight;                            // 0x00B0(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         BuildingDroneWarningHeight;                        // 0x00B4(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         MaxDroneRailLenght;                                // 0x00B8(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          Cheats;                                            // 0x00BC(0x0001)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_BD[0x3];                                       // 0x00BD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UMaterialInstanceConstant> GridMaterialInstance;                            // 0x00C0(0x0028)(Edit, Config, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UMaterialParameterCollection> GridMaterialParametersCollection;             // 0x00E8(0x0028)(Edit, Config, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UMaterialInstanceConstant> CollisionBoxMaterialInstance;                    // 0x0110(0x0028)(Edit, Config, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         GridDistanceFadeout;                               // 0x0138(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_13C[0x4];                                      // 0x013C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TSoftObjectPtr<class UStaticMesh>             PlatformSnapIcon;                                  // 0x0140(0x0028)(Edit, Config, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UMaterialInstanceConstant> PlatformSnapIconMaterialInstance;                // 0x0168(0x0028)(Edit, Config, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	TSoftObjectPtr<class UMaterialInstanceConstant> ConnectorBoxOutlineMaterialInstance;             // 0x0190(0x0028)(Edit, Config, DisableEditOnInstance, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FColor                                 CollisionColor;                                    // 0x01B8(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         FixedDroneRailConstInstances;                      // 0x01BC(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxDynamicFoundationCount;                         // 0x01C0(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DynamicFoundationElemStabilityCost;                // 0x01C4(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         DynamicFoundationMaxStabilityElemCount;            // 0x01C8(0x0004)(Edit, ZeroConstructor, Config, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_1CC[0x4];                                      // 0x01CC(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuActorPlacementDeveloperSettings")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuActorPlacementDeveloperSettings")
	}
	static class UAuActorPlacementDeveloperSettings* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuActorPlacementDeveloperSettings>();
	}
};
DUMPER7_ASSERTS_UAuActorPlacementDeveloperSettings;

// Class AuActorPlacement.AuActorPlacementFunctionLibrary
// 0x0000 (0x0028 - 0x0028)
class UAuActorPlacementFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static const class UAuActorPlacementData* GetPayloadPlacementData(const struct FAuAPPayloadDataHandle& InHandle);
	static struct FAuAPSplineActorPayloadData GetSplineActorData(const struct FAuAPPayloadDataHandle& InHandle);
	static struct FAuAPPayloadDataHandle MakePayloadHandle(const class UAuActorPlacementData* InPlacementData);
	static struct FAuAPPayloadDataHandle MakeSplineActorData(class USplineComponent* InSpline, const class UAuActorPlacementData* InPlacementData, const struct FActorInstanceHandle& StartActor, const struct FActorInstanceHandle& EndActor);
	static void SetSplineActorData(const struct FAuAPPayloadDataHandle& InHandle, class USplineComponent* InSpline);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuActorPlacementFunctionLibrary")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuActorPlacementFunctionLibrary")
	}
	static class UAuActorPlacementFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuActorPlacementFunctionLibrary>();
	}
};
DUMPER7_ASSERTS_UAuActorPlacementFunctionLibrary;

// Class AuActorPlacement.AuActorPlacementSocketData
// 0x0020 (0x0050 - 0x0030)
class UAuActorPlacementSocketData final : public UDataAsset
{
public:
	class FName                                   Name_0;                                            // 0x0030(0x0008)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Tag;                                               // 0x0038(0x0010)(Edit, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         Radius;                                            // 0x0048(0x0004)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuActorPlacementSocketData")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuActorPlacementSocketData")
	}
	static class UAuActorPlacementSocketData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuActorPlacementSocketData>();
	}
};
DUMPER7_ASSERTS_UAuActorPlacementSocketData;

// Class AuActorPlacement.AuActorPlacementSocketsComponent
// 0x0010 (0x00C8 - 0x00B8)
class UAuActorPlacementSocketsComponent final : public UActorComponent
{
public:
	TArray<struct FAuActorPlacementSingleSocketData> Sockets;                                        // 0x00B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, Protected, NativeAccessSpecifierProtected)

public:
	void SetAllSocketsActive(bool bActive);

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuActorPlacementSocketsComponent")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuActorPlacementSocketsComponent")
	}
	static class UAuActorPlacementSocketsComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuActorPlacementSocketsComponent>();
	}
};
DUMPER7_ASSERTS_UAuActorPlacementSocketsComponent;

// Class AuActorPlacement.AuActorPlacingConditionsData
// 0x02D0 (0x0300 - 0x0030)
class UAuActorPlacingConditionsData : public UDataAsset
{
public:
	struct FAuAPGridSettings                      Grid;                                              // 0x0030(0x0080)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	struct FAuAPRotationSnappingSettings          RotSnapping;                                       // 0x00B0(0x0020)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bCheckSurfaceAngleConditions;                      // 0x00D0(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_D1[0x7];                                       // 0x00D1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAuAPSurfaceAngleConditions            SurfaceAngleConditions;                            // 0x00D8(0x0020)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	bool                                          bCheckStability;                                   // 0x00F8(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_F9[0x7];                                       // 0x00F9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAuAPOffsetSettings                    OffsetSettings;                                    // 0x0100(0x0020)(Edit, NoDestructor, NativeAccessSpecifierPublic)
	ECollisionChannel                             PlaceTraceChannel;                                 // 0x0120(0x0001)(Edit, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_121[0x7];                                      // 0x0121(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TSet<EPhysicalSurface>                        AllowedPhysicalSurfaces;                           // 0x0128(0x0050)(Edit, NativeAccessSpecifierPublic)
	struct FBodyInstance                          HelperCollisionResponse;                           // 0x0178(0x0180)(Edit, NativeAccessSpecifierPublic)
	uint8                                         Pad_2F8[0x8];                                      // 0x02F8(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuActorPlacingConditionsData")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuActorPlacingConditionsData")
	}
	static class UAuActorPlacingConditionsData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuActorPlacingConditionsData>();
	}
};
DUMPER7_ASSERTS_UAuActorPlacingConditionsData;

// Class AuActorPlacement.AuAPHelperActor
// 0x0000 (0x02A8 - 0x02A8)
class AAuAPHelperActor : public AActor
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuAPHelperActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuAPHelperActor")
	}
	static class AAuAPHelperActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAuAPHelperActor>();
	}
};
DUMPER7_ASSERTS_AAuAPHelperActor;

// Class AuActorPlacement.AuAPMassRepresentationActorManagement
// 0x0000 (0x0028 - 0x0028)
class UAuAPMassRepresentationActorManagement final : public UMassRepresentationActorManagement
{
public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuAPMassRepresentationActorManagement")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuAPMassRepresentationActorManagement")
	}
	static class UAuAPMassRepresentationActorManagement* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuAPMassRepresentationActorManagement>();
	}
};
DUMPER7_ASSERTS_UAuAPMassRepresentationActorManagement;

// Class AuActorPlacement.AuAPMassSpawnProcessor
// 0x0350 (0x0410 - 0x00C0)
class UAuAPMassSpawnProcessor final : public UMassProcessor
{
public:
	uint8                                         Pad_C0[0x350];                                     // 0x00C0(0x0350)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuAPMassSpawnProcessor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuAPMassSpawnProcessor")
	}
	static class UAuAPMassSpawnProcessor* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuAPMassSpawnProcessor>();
	}
};
DUMPER7_ASSERTS_UAuAPMassSpawnProcessor;

// Class AuActorPlacement.AuAPSimpleMassSpawner
// 0x0040 (0x02E8 - 0x02A8)
class AAuAPSimpleMassSpawner : public AActor
{
public:
	uint8                                         Pad_2A8[0x20];                                     // 0x02A8(0x0020)(Fixing Size After Last Property [ Dumper-7 ])
	class UAuActorPlacementData*                  PlacementData;                                     // 0x02C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	bool                                          bSpawnerDisableCollision;                          // 0x02D0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)
	uint8                                         Pad_2D1[0x3];                                      // 0x02D1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGuid                                  Guid;                                              // 0x02D4(0x0010)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, EditConst, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_2E4[0x4];                                      // 0x02E4(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void DoSpawning();
	void ForceEditorUpdateMeshes();
	void ResetGuid();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuAPSimpleMassSpawner")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuAPSimpleMassSpawner")
	}
	static class AAuAPSimpleMassSpawner* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAuAPSimpleMassSpawner>();
	}
};
DUMPER7_ASSERTS_AAuAPSimpleMassSpawner;

// Class AuActorPlacement.AuBuildingGridSubsystem
// 0x0050 (0x0080 - 0x0030)
class UAuBuildingGridSubsystem final : public UWorldSubsystem
{
public:
	uint8                                         Pad_30[0x8];                                       // 0x0030(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class UAuActorPlacementDeveloperSettings*     PlacementDeveloperSettings;                        // 0x0038(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	class UStaticMesh*                            CollisionBorderStaticMesh;                         // 0x0040(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	class UMaterialInstanceConstant*              CollisionBorderMaterialInstanceConstant;           // 0x0048(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	class UMaterialInstanceConstant*              ConnectorBoxOutlineMaterialInstance;               // 0x0050(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	class UMaterialInstanceConstant*              ConnectorIconMaterialInstanceConstant;             // 0x0058(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	class UMaterialParameterCollectionInstance*   GridMaterialParametersCollectionInstance;          // 0x0060(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	class UStaticMesh*                            BoxMesh;                                           // 0x0068(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	class UStaticMesh*                            ConnectorIconMesh;                                 // 0x0070(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)
	class ADecalActor*                            DecalActor;                                        // 0x0078(0x0008)(ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash, NativeAccessSpecifierPublic, TObjectPtr)

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuBuildingGridSubsystem")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuBuildingGridSubsystem")
	}
	static class UAuBuildingGridSubsystem* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAuBuildingGridSubsystem>();
	}
};
DUMPER7_ASSERTS_UAuBuildingGridSubsystem;

// Class AuActorPlacement.AuEvaporatingWaterActor
// 0x0048 (0x02F0 - 0x02A8)
class AAuEvaporatingWaterActor final : public AActor
{
public:
	TMulticastInlineDelegate<void()>              BuildingGridEnabledDelegate;                       // 0x02A8(0x0018)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	TMulticastInlineDelegate<void()>              OnBuildingGridDisabledDelegate;                    // 0x02C0(0x0018)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	double                                        SignificanceDistanceThreshold;                     // 0x02D8(0x0008)(Edit, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPrivate)
	uint8                                         Pad_2E0[0x10];                                     // 0x02E0(0x0010)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void BP_OnPostBecameInsignificant();
	void BP_OnPostBecameSignificant();

public:
	static class UClass* StaticClass()
	{
		STATIC_CLASS_IMPL("AuEvaporatingWaterActor")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"AuEvaporatingWaterActor")
	}
	static class AAuEvaporatingWaterActor* GetDefaultObj()
	{
		return GetDefaultObjImpl<AAuEvaporatingWaterActor>();
	}
};
DUMPER7_ASSERTS_AAuEvaporatingWaterActor;

SDK_NAMESPACE_END
