#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Animal_Crab_Character

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "E_Animal_Crab_TentaclesState_structs.hpp"
#include "BP_BaseAI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Animal_Crab_Character.BP_Animal_Crab_Character_C
// 0x0130 (0x0E30 - 0x0D00)
class ABP_Animal_Crab_Character_C final : public ABP_BaseAI_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Animal_Crab_Character_C;         // 0x0D00(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Tentacle8;                                         // 0x0D08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tentacle7;                                         // 0x0D10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tentacle6;                                         // 0x0D18(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tentacle5;                                         // 0x0D20(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tentacle4;                                         // 0x0D28(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tentacle3;                                         // 0x0D30(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tentacle1;                                         // 0x0D38(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Tentacle2;                                         // 0x0D40(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCrAiAnimalCrabUpdateStateComponent*    CrAiAnimalCrabUpdateState;                         // 0x0D48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         SimulateCatchTimeline_Lerp_hide_289BD3004813B7E95FAE37B544C91B24; // 0x0D50(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            SimulateCatchTimeline__Direction_289BD3004813B7E95FAE37B544C91B24; // 0x0D54(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D55[0x3];                                      // 0x0D55(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     SimulateCatchTimeline;                             // 0x0D58(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	TArray<class UStaticMeshComponent*>           Tentacles;                                         // 0x0D60(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<double>                                WakeUpOffsets;                                     // 0x0D70(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UCurveFloat*                            Curve;                                             // 0x0D80(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               SelectedTentacle;                                  // 0x0D88(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          AreTentaclesHiddenState;                           // 0x0D90(0x0001)(Edit, BlueprintVisible, Net, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, RepNotify, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_D91[0x7];                                      // 0x0D91(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	double                                        Progress;                                          // 0x0D98(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        HideSpeed;                                         // 0x0DA0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        UnhideSpeed;                                       // 0x0DA8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	E_Animal_Crab_TentaclesState                  TentaclesAnimState;                                // 0x0DB0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DB1[0x3];                                      // 0x0DB1(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         DeltaSeconds;                                      // 0x0DB4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        TimeToNextCatch;                                   // 0x0DB8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          IsCatchActive;                                     // 0x0DC0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_DC1[0x7];                                      // 0x0DC1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMap<class ACrCharacterBase*, double>         CharactersHitMap;                                  // 0x0DC8(0x0050)(Edit, BlueprintVisible, DisableEditOnTemplate, DisableEditOnInstance)
	double                                        HitDamageDelay;                                    // 0x0E18(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      Niagara;                                           // 0x0E20(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void StopCatach();
	void SimulateCatchTimeline__UpdateFunc();
	void SimulateCatchTimeline__FinishedFunc();
	void SimulateCatch();
	void SetTentaclesHidden(bool bHidden);
	void SetNiagaraActivity(bool NewActive);
	void RegisterFXEvent(const struct FGameplayTag& FXEventTag);
	void ReceiveTick(float DeltaSeconds_ReceiveTick);
	void ReceiveEndPlay(EEndPlayReason EndPlayReason_ReceiveEndPlay);
	void ReceiveBeginPlay();
	void OnRep_AreTentaclesHiddenState();
	void OnPrepareForPooling();
	void OnPrepareForGame();
	class UCrAiAnimalCrabUpdateStateComponent* GetCrabUpdateStateComponent();
	void ExecuteUbergraph_BP_Animal_Crab_Character(int32 EntryPoint);
	void BndEvt__BP_Animal_Crab_Character_CapsuleComponent_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit);
	bool AreTentaclesHidden();

	void OnMeshVisibilityUpdated(bool bIsMeshHidden_OnMeshVisibilityUpdated) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Animal_Crab_Character_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Animal_Crab_Character_C")
	}
	static class ABP_Animal_Crab_Character_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Animal_Crab_Character_C>();
	}
};
DUMPER7_ASSERTS_ABP_Animal_Crab_Character_C;

SDK_NAMESPACE_END
