#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Assembler

#include "Basic.hpp"

#include "BP_Assembler_classes.hpp"
#include "BP_Assembler_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_Assembler.BP_Assembler_C.SetupSkeletalMesh
// (Event, Public, BlueprintEvent)

void ABP_Assembler_C::SetupSkeletalMesh()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assembler_C", "SetupSkeletalMesh");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Assembler.BP_Assembler_C.OnItemCraftingComplete
// (Event, Public, BlueprintEvent)

void ABP_Assembler_C::OnItemCraftingComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assembler_C", "OnItemCraftingComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_Assembler.BP_Assembler_C.OnBuildingStateChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// ECrBuildingState                        InState_OnBuildingStateChanged                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Assembler_C::OnBuildingStateChanged(ECrBuildingState InState_OnBuildingStateChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assembler_C", "OnBuildingStateChanged");

	Params::BP_Assembler_C_OnBuildingStateChanged Parms{};

	Parms.InState_OnBuildingStateChanged = InState_OnBuildingStateChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Assembler.BP_Assembler_C.ExecuteUbergraph_BP_Assembler
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_Assembler_C::ExecuteUbergraph_BP_Assembler(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assembler_C", "ExecuteUbergraph_BP_Assembler");

	Params::BP_Assembler_C_ExecuteUbergraph_BP_Assembler Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_Assembler.BP_Assembler_C.Get Meshes
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// class USceneComponent*                  Static                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// class USceneComponent*                  Animated                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// TArray<class UMeshComponent*>*          NewParam                                               (Parm, OutParm, ContainsInstancedReference)

void ABP_Assembler_C::Get_Meshes(class USceneComponent* Static, class USceneComponent* Animated, TArray<class UMeshComponent*>* NewParam) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_Assembler_C", "Get Meshes");

	Params::BP_Assembler_C_Get_Meshes Parms{};

	Parms.Static = Static;
	Parms.Animated = Animated;

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = std::move(Parms.NewParam);
}


SDK_NAMESPACE_END
