#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AnimNotifyState_SetVisibilityBasedUpdateRate

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AnimNotifyState_SetVisibilityBasedUpdateRate.BP_AnimNotifyState_SetVisibilityBasedUpdateRate_C
// 0x0000 (0x0030 - 0x0030)
class UBP_AnimNotifyState_SetVisibilityBasedUpdateRate_C final : public UAnimNotifyState
{
public:
	bool Received_NotifyEnd(class USkeletalMeshComponent* MeshComp_Received_NotifyEnd, class UAnimSequenceBase* Animation_Received_NotifyEnd, const struct FAnimNotifyEventReference& EventReference_Received_NotifyEnd) const;
	bool Received_NotifyBegin(class USkeletalMeshComponent* MeshComp_Received_NotifyBegin, class UAnimSequenceBase* Animation_Received_NotifyBegin, float TotalDuration_Received_NotifyBegin, const struct FAnimNotifyEventReference& EventReference_Received_NotifyBegin) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AnimNotifyState_SetVisibilityBasedUpdateRate_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AnimNotifyState_SetVisibilityBasedUpdateRate_C")
	}
	static class UBP_AnimNotifyState_SetVisibilityBasedUpdateRate_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AnimNotifyState_SetVisibilityBasedUpdateRate_C>();
	}
};
DUMPER7_ASSERTS_UBP_AnimNotifyState_SetVisibilityBasedUpdateRate_C;

SDK_NAMESPACE_END
