#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AnimNotifyState_AddMovementVectorInput

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_AnimNotifyState_AddMovementVectorInput.BP_AnimNotifyState_AddMovementVectorInput_C
// 0x0010 (0x0040 - 0x0030)
class UBP_AnimNotifyState_AddMovementVectorInput_C final : public UAnimNotifyState
{
public:
	double                                        StartInput;                                        // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        EndInput;                                          // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool Received_NotifyTick(class USkeletalMeshComponent* MeshComp_Received_NotifyTick, class UAnimSequenceBase* Animation_Received_NotifyTick, float FrameDeltaTime_Received_NotifyTick, const struct FAnimNotifyEventReference& EventReference_Received_NotifyTick) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_AnimNotifyState_AddMovementVectorInput_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_AnimNotifyState_AddMovementVectorInput_C")
	}
	static class UBP_AnimNotifyState_AddMovementVectorInput_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_AnimNotifyState_AddMovementVectorInput_C>();
	}
};
DUMPER7_ASSERTS_UBP_AnimNotifyState_AddMovementVectorInput_C;

SDK_NAMESPACE_END
