#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CloningBed

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Chimera_structs.hpp"
#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CloningBed.BP_CloningBed_C
// 0x0070 (0x0750 - 0x06E0)
class ABP_CloningBed_C : public ACrSpawnPointBuilding
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x06E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      NS_CloningBed;                                     // 0x06E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_CloningBed_main_body_top;                       // 0x06F0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SK_Cloningbed;                                     // 0x06F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_CloningBed_door_R;                              // 0x0700(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_CloningBed_door_L;                              // 0x0708(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_Cloningbed_door_center;                         // 0x0710(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         BedOwnedTaken_value_BedOwnedTaken_FBC7F53C4321F647EA6402B789AABC6A; // 0x0718(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            BedOwnedTaken_value__Direction_FBC7F53C4321F647EA6402B789AABC6A; // 0x071C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_71D[0x3];                                      // 0x071D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     BedOwnedTaken_value;                               // 0x0720(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         BedFree_value_BedFree_9322525842C472872A1788863BFF508E; // 0x0728(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            BedFree_value__Direction_9322525842C472872A1788863BFF508E; // 0x072C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_72D[0x3];                                      // 0x072D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     BedFree_value;                                     // 0x0730(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	float                                         Window_Opacity_Opacity_ED547ABE48A0BDCBDE2572BEFF8943BE; // 0x0738(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Window_Opacity__Direction_ED547ABE48A0BDCBDE2572BEFF8943BE; // 0x073C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_73D[0x3];                                      // 0x073D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Window_Opacity;                                    // 0x0740(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               BedWindowMI;                                       // 0x0748(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void Window_Opacity__UpdateFunc();
	void Window_Opacity__FinishedFunc();
	void ReceiveBeginPlay();
	void OnBuildingOwnershipChanged(ECrBuildingOwnership NewOwnership);
	void ExecuteUbergraph_BP_CloningBed(int32 EntryPoint);
	void ChangeWindowMaterial(class UMaterialInterface* Material);
	void BedOwnedTaken_value__UpdateFunc();
	void BedOwnedTaken_value__FinishedFunc();
	void BedFree_value__UpdateFunc();
	void BedFree_value__FinishedFunc();

	class FText GetInteractionAdditionalTextFromOwnership(ECrBuildingOwnership InOwnership) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CloningBed_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CloningBed_C")
	}
	static class ABP_CloningBed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CloningBed_C>();
	}
};
DUMPER7_ASSERTS_ABP_CloningBed_C;

SDK_NAMESPACE_END
