#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CoolerActive_Helper

#include "Basic.hpp"

#include "BP_ChimeraPlacementHelperReplicatedBase_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_CoolerActive_Helper.BP_CoolerActive_Helper_C
// 0x0010 (0x0A70 - 0x0A60)
class ABP_CoolerActive_Helper_C final : public ABP_ChimeraPlacementHelperReplicatedBase_C
{
public:
	int32                                         Grid_Size_X;                                       // 0x0A58(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         Grid_Size_Y;                                       // 0x0A5C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	double                                        Tile_Size;                                         // 0x0A60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_CoolerActive_Helper_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_CoolerActive_Helper_C")
	}
	static class ABP_CoolerActive_Helper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_CoolerActive_Helper_C>();
	}
};
DUMPER7_ASSERTS_ABP_CoolerActive_Helper_C;

SDK_NAMESPACE_END
