#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CloningBed_Lander

#include "Basic.hpp"

#include "BP_CloningBed_Lander_classes.hpp"
#include "BP_CloningBed_Lander_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_CloningBed_Lander.BP_CloningBed_Lander_C.K2_GetInteractionActionText
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             ReturnValue_K2_GetInteractionActionText                (Parm, OutParm, ReturnParm)

class FText ABP_CloningBed_Lander_C::K2_GetInteractionActionText()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_CloningBed_Lander_C", "K2_GetInteractionActionText");

	Params::BP_CloningBed_Lander_C_K2_GetInteractionActionText Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


SDK_NAMESPACE_END
