#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroneVerticalConnector

#include "Basic.hpp"

#include "BP_DroneVerticalConnector_classes.hpp"
#include "BP_DroneVerticalConnector_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_DroneVerticalConnector.BP_DroneVerticalConnector_C.OnTierSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// int32                                   NewTier_OnTierSet                                      (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DroneVerticalConnector_C::OnTierSet(int32 NewTier_OnTierSet)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroneVerticalConnector_C", "OnTierSet");

	Params::BP_DroneVerticalConnector_C_OnTierSet Parms{};

	Parms.NewTier_OnTierSet = NewTier_OnTierSet;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_DroneVerticalConnector.BP_DroneVerticalConnector_C.ExecuteUbergraph_BP_DroneVerticalConnector
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_DroneVerticalConnector_C::ExecuteUbergraph_BP_DroneVerticalConnector(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_DroneVerticalConnector_C", "ExecuteUbergraph_BP_DroneVerticalConnector");

	Params::BP_DroneVerticalConnector_C_ExecuteUbergraph_BP_DroneVerticalConnector Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
