#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroneVerticalConnector_Helper_T1

#include "Basic.hpp"

#include "BP_PlacementHelperReplicated_VerticalConnector_classes.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DroneVerticalConnector_Helper_T1.BP_DroneVerticalConnector_Helper_T1_C
// 0x0020 (0x0AF0 - 0x0AD0)
class ABP_DroneVerticalConnector_Helper_T1_C : public ABP_PlacementHelperReplicated_VerticalConnector_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_DroneVerticalConnector_Helper_T1_C; // 0x0AD0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FVector                                TRUE_0;                                            // 0x0AD8(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_DroneVerticalConnector_Helper_T1(int32 EntryPoint);
	void OnSetReplacingExistingActor(bool bSet);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DroneVerticalConnector_Helper_T1_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DroneVerticalConnector_Helper_T1_C")
	}
	static class ABP_DroneVerticalConnector_Helper_T1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DroneVerticalConnector_Helper_T1_C>();
	}
};
DUMPER7_ASSERTS_ABP_DroneVerticalConnector_Helper_T1_C;

SDK_NAMESPACE_END
