#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroneRailSupportHelper

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DroneRailSupportHelper.BP_DroneRailSupportHelper_C
// 0x0020 (0x0A60 - 0x0A40)
class ABP_DroneRailSupportHelper_C final : public ACrAPHelperActorBase
{
public:
	uint8                                         Pad_A38[0x8];                                      // 0x0A38(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0A40(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UInstancedStaticMeshComponent*          TileIndicatorsISM;                                 // 0x0A48(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UMaterialInstanceDynamic*               TileIndicatorISMDynamicMaterial;                   // 0x0A50(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void SetMeshColor(const struct FLinearColor& Color_SetMeshColor);
	void OnFoundationSetUp(const TArray<struct FTransform>& FoundationTransforms);
	void ExecuteUbergraph_BP_DroneRailSupportHelper(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DroneRailSupportHelper_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DroneRailSupportHelper_C")
	}
	static class ABP_DroneRailSupportHelper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DroneRailSupportHelper_C>();
	}
};
DUMPER7_ASSERTS_ABP_DroneRailSupportHelper_C;

SDK_NAMESPACE_END
