#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DynamicPillar

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DynamicPillar.BP_DynamicPillar_C
// 0x0030 (0x08F0 - 0x08C0)
class ABP_DynamicPillar_C final : public ACrDynamicPillar
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBoxComponent*                          Box;                                               // 0x08C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Top;                                               // 0x08D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCrInteriorsMapperBoxComponent*         CrInteriorsMapperBox;                              // 0x08D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UInstancedStaticMeshComponent*          MainMesh;                                          // 0x08E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Bottom;                                            // 0x08E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void ExecuteUbergraph_BP_DynamicPillar(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DynamicPillar_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DynamicPillar_C")
	}
	static class ABP_DynamicPillar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DynamicPillar_C>();
	}
};
DUMPER7_ASSERTS_ABP_DynamicPillar_C;

SDK_NAMESPACE_END
