#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroneLane_3_390

#include "Basic.hpp"

#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_DroneLane_3_390.BP_DroneLane_3_390_C
// 0x0020 (0x06E0 - 0x06C0)
class ABP_DroneLane_3_390_C final : public ACrDronePathPoint
{
public:
	class UStaticMeshComponent*                   Pole;                                              // 0x06C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   PlacementHelper;                                   // 0x06C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   MainMesh;                                          // 0x06D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAuActorPlacementSocketsComponent*      AuActorPlacementSockets;                           // 0x06D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DroneLane_3_390_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DroneLane_3_390_C")
	}
	static class ABP_DroneLane_3_390_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DroneLane_3_390_C>();
	}
};
DUMPER7_ASSERTS_ABP_DroneLane_3_390_C;

SDK_NAMESPACE_END
