#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_DroneJunction_4_250_Helper

#include "Basic.hpp"

#include "BP_PlacementHelperReplicatedBase_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_DroneJunction_4_250_Helper.BP_DroneJunction_4_250_Helper_C
// 0x0000 (0x08B0 - 0x08B0)
class ABP_DroneJunction_4_250_Helper_C final : public ABP_PlacementHelperReplicatedBase_C
{
public:
	class UStaticMeshComponent*                   Pole;                                              // 0x08A8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_DroneJunction_4_250_Helper_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_DroneJunction_4_250_Helper_C")
	}
	static class ABP_DroneJunction_4_250_Helper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_DroneJunction_4_250_Helper_C>();
	}
};
DUMPER7_ASSERTS_ABP_DroneJunction_4_250_Helper_C;

}

