#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EngineControlStation_ItemPrinter

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Chimera_structs.hpp"
#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_EngineControlStation_ItemPrinter.BP_EngineControlStation_ItemPrinter_C
// 0x0070 (0x07C0 - 0x0750)
class ABP_EngineControlStation_ItemPrinter_C final : public ACrCrafter
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0750(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UChildActorComponent*                   BP_MaterializedItemCrate;                          // 0x0758(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NS_ItemPrinter;                                    // 0x0760(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_EngineControlStation_ItemPrinter_main_body_addons; // 0x0768(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_EngineControlStation_ItemPrinter_ring_holder;   // 0x0770(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_EngineControlStation_ItemPrinter_ring;          // 0x0778(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_EngineControlStation_ItemPrinter_main_body;     // 0x0780(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USkeletalMeshComponent*                 SK_EngineControlStation_ItemPrinter;               // 0x0788(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Animated;                                          // 0x0790(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Static;                                            // 0x0798(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Meshes;                                            // 0x07A0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class UMeshComponent*>                 tab_meshes;                                        // 0x07A8(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class UAudioComponent*                        WorkingLoopSound;                                  // 0x07B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void SetupSkeletalMesh();
	void ReceiveBeginPlay();
	void OnUIOpened(bool bOpened_OnUIOpened);
	void OnItemCraftingComplete();
	void OnBuildingStateChanged(ECrBuildingState InState_OnBuildingStateChanged);
	void Get_Meshes(class USceneComponent* Static, class USceneComponent* Animated, TArray<class UMeshComponent*>* NewParam);
	void ExecuteUbergraph_BP_EngineControlStation_ItemPrinter(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_EngineControlStation_ItemPrinter_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_EngineControlStation_ItemPrinter_C")
	}
	static class ABP_EngineControlStation_ItemPrinter_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_EngineControlStation_ItemPrinter_C>();
	}
};
DUMPER7_ASSERTS_ABP_EngineControlStation_ItemPrinter_C;

SDK_NAMESPACE_END
