#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ExporterTier2

#include "Basic.hpp"

#include "BP_ExporterTier2_classes.hpp"
#include "BP_ExporterTier2_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_ExporterTier2.BP_ExporterTier2_C.Attach_meshes
// (BlueprintCallable, BlueprintEvent)

void ABP_ExporterTier2_C::Attach_meshes()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ExporterTier2_C", "Attach_meshes");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ExporterTier2.BP_ExporterTier2_C.ExecuteUbergraph_BP_ExporterTier2
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ExporterTier2_C::ExecuteUbergraph_BP_ExporterTier2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ExporterTier2_C", "ExecuteUbergraph_BP_ExporterTier2");

	Params::BP_ExporterTier2_C_ExecuteUbergraph_BP_ExporterTier2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ExporterTier2.BP_ExporterTier2_C.OnBuildingStateChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// ECrBuildingState                        InState                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ExporterTier2_C::OnBuildingStateChanged(ECrBuildingState InState)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ExporterTier2_C", "OnBuildingStateChanged");

	Params::BP_ExporterTier2_C_OnBuildingStateChanged Parms{};

	Parms.InState = InState;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ExporterTier2.BP_ExporterTier2_C.OnCorporationChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// class FName                             NewCorporation                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_ExporterTier2_C::OnCorporationChanged(class FName NewCorporation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ExporterTier2_C", "OnCorporationChanged");

	Params::BP_ExporterTier2_C_OnCorporationChanged Parms{};

	Parms.NewCorporation = NewCorporation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_ExporterTier2.BP_ExporterTier2_C.OnItemCraftingComplete
// (Event, Public, BlueprintEvent)

void ABP_ExporterTier2_C::OnItemCraftingComplete()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ExporterTier2_C", "OnItemCraftingComplete");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ExporterTier2.BP_ExporterTier2_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_ExporterTier2_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ExporterTier2_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_ExporterTier2.BP_ExporterTier2_C.UserConstructionScript
// (Event, Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABP_ExporterTier2_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ExporterTier2_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
