#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Grenade

#include "Basic.hpp"

#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Grenade.BP_Grenade_C
// 0x0000 (0x1300 - 0x1300)
class UBP_Grenade_C final : public UCrGrenadeWeaponItemDataBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Grenade_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Grenade_C")
	}
	static class UBP_Grenade_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Grenade_C>();
	}
};
DUMPER7_ASSERTS_UBP_Grenade_C;

SDK_NAMESPACE_END
