#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HabitatWindowsFireSmall

#include "Basic.hpp"

#include "BP_HabitatWindowsFireSmall_classes.hpp"
#include "BP_HabitatWindowsFireSmall_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_HabitatWindowsFireSmall.BP_HabitatWindowsFireSmall_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_HabitatWindowsFireSmall_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HabitatWindowsFireSmall_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HabitatWindowsFireSmall.BP_HabitatWindowsFireSmall_C.OnEnviroWaveTick
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEnviroWave                             WaveType_OnEnviroWaveTick                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEnviroWaveStage                        WaveStage_OnEnviroWaveTick                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FCrEnviroWaveSettings&     WaveSettings_OnEnviroWaveTick                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// float                                   WaveProgress_OnEnviroWaveTick                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HabitatWindowsFireSmall_C::OnEnviroWaveTick(EEnviroWave WaveType_OnEnviroWaveTick, EEnviroWaveStage WaveStage_OnEnviroWaveTick, const struct FCrEnviroWaveSettings& WaveSettings_OnEnviroWaveTick, float WaveProgress_OnEnviroWaveTick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HabitatWindowsFireSmall_C", "OnEnviroWaveTick");

	Params::BP_HabitatWindowsFireSmall_C_OnEnviroWaveTick Parms{};

	Parms.WaveType_OnEnviroWaveTick = WaveType_OnEnviroWaveTick;
	Parms.WaveStage_OnEnviroWaveTick = WaveStage_OnEnviroWaveTick;
	Parms.WaveSettings_OnEnviroWaveTick = std::move(WaveSettings_OnEnviroWaveTick);
	Parms.WaveProgress_OnEnviroWaveTick = WaveProgress_OnEnviroWaveTick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HabitatWindowsFireSmall.BP_HabitatWindowsFireSmall_C.OnEnviroWaveStarted
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEnviroWave                             WaveType_OnEnviroWaveStarted                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEnviroWaveStage                        WaveStage_OnEnviroWaveStarted                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FCrEnviroWaveSettings&     WaveSettings_OnEnviroWaveStarted                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// float                                   WaveProgress_OnEnviroWaveStarted                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HabitatWindowsFireSmall_C::OnEnviroWaveStarted(EEnviroWave WaveType_OnEnviroWaveStarted, EEnviroWaveStage WaveStage_OnEnviroWaveStarted, const struct FCrEnviroWaveSettings& WaveSettings_OnEnviroWaveStarted, float WaveProgress_OnEnviroWaveStarted)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HabitatWindowsFireSmall_C", "OnEnviroWaveStarted");

	Params::BP_HabitatWindowsFireSmall_C_OnEnviroWaveStarted Parms{};

	Parms.WaveType_OnEnviroWaveStarted = WaveType_OnEnviroWaveStarted;
	Parms.WaveStage_OnEnviroWaveStarted = WaveStage_OnEnviroWaveStarted;
	Parms.WaveSettings_OnEnviroWaveStarted = std::move(WaveSettings_OnEnviroWaveStarted);
	Parms.WaveProgress_OnEnviroWaveStarted = WaveProgress_OnEnviroWaveStarted;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HabitatWindowsFireSmall.BP_HabitatWindowsFireSmall_C.OnEnviroWaveForced
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEnviroWave                             WaveType_OnEnviroWaveForced                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEnviroWaveStage                        WaveStage_OnEnviroWaveForced                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FCrEnviroWaveSettings&     WaveSettings_OnEnviroWaveForced                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// float                                   WaveProgress_OnEnviroWaveForced                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HabitatWindowsFireSmall_C::OnEnviroWaveForced(EEnviroWave WaveType_OnEnviroWaveForced, EEnviroWaveStage WaveStage_OnEnviroWaveForced, const struct FCrEnviroWaveSettings& WaveSettings_OnEnviroWaveForced, float WaveProgress_OnEnviroWaveForced)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HabitatWindowsFireSmall_C", "OnEnviroWaveForced");

	Params::BP_HabitatWindowsFireSmall_C_OnEnviroWaveForced Parms{};

	Parms.WaveType_OnEnviroWaveForced = WaveType_OnEnviroWaveForced;
	Parms.WaveStage_OnEnviroWaveForced = WaveStage_OnEnviroWaveForced;
	Parms.WaveSettings_OnEnviroWaveForced = std::move(WaveSettings_OnEnviroWaveForced);
	Parms.WaveProgress_OnEnviroWaveForced = WaveProgress_OnEnviroWaveForced;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HabitatWindowsFireSmall.BP_HabitatWindowsFireSmall_C.OnEnviroWaveFinished
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEnviroWave                             WaveType_OnEnviroWaveFinished                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FCrEnviroWaveSettings&     WaveSettings_OnEnviroWaveFinished                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void ABP_HabitatWindowsFireSmall_C::OnEnviroWaveFinished(EEnviroWave WaveType_OnEnviroWaveFinished, const struct FCrEnviroWaveSettings& WaveSettings_OnEnviroWaveFinished)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HabitatWindowsFireSmall_C", "OnEnviroWaveFinished");

	Params::BP_HabitatWindowsFireSmall_C_OnEnviroWaveFinished Parms{};

	Parms.WaveType_OnEnviroWaveFinished = WaveType_OnEnviroWaveFinished;
	Parms.WaveSettings_OnEnviroWaveFinished = std::move(WaveSettings_OnEnviroWaveFinished);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HabitatWindowsFireSmall.BP_HabitatWindowsFireSmall_C.OnEnviroWaveCanceled
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEnviroWave                             WaveType_OnEnviroWaveCanceled                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEnviroWaveStage                        WaveStage_OnEnviroWaveCanceled                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FCrEnviroWaveSettings&     WaveSettings_OnEnviroWaveCanceled                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void ABP_HabitatWindowsFireSmall_C::OnEnviroWaveCanceled(EEnviroWave WaveType_OnEnviroWaveCanceled, EEnviroWaveStage WaveStage_OnEnviroWaveCanceled, const struct FCrEnviroWaveSettings& WaveSettings_OnEnviroWaveCanceled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HabitatWindowsFireSmall_C", "OnEnviroWaveCanceled");

	Params::BP_HabitatWindowsFireSmall_C_OnEnviroWaveCanceled Parms{};

	Parms.WaveType_OnEnviroWaveCanceled = WaveType_OnEnviroWaveCanceled;
	Parms.WaveStage_OnEnviroWaveCanceled = WaveStage_OnEnviroWaveCanceled;
	Parms.WaveSettings_OnEnviroWaveCanceled = std::move(WaveSettings_OnEnviroWaveCanceled);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HabitatWindowsFireSmall.BP_HabitatWindowsFireSmall_C.ExecuteUbergraph_BP_HabitatWindowsFireSmall
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HabitatWindowsFireSmall_C::ExecuteUbergraph_BP_HabitatWindowsFireSmall(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HabitatWindowsFireSmall_C", "ExecuteUbergraph_BP_HabitatWindowsFireSmall");

	Params::BP_HabitatWindowsFireSmall_C_ExecuteUbergraph_BP_HabitatWindowsFireSmall Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
