#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_HabitatPostProcess

#include "Basic.hpp"

#include "BP_HabitatPostProcess_classes.hpp"
#include "BP_HabitatPostProcess_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_HabitatPostProcess.BP_HabitatPostProcess_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABP_HabitatPostProcess_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HabitatPostProcess_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_HabitatPostProcess.BP_HabitatPostProcess_C.OnEnviroWaveTick
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EEnviroWave                             WaveType_OnEnviroWaveTick                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// EEnviroWaveStage                        WaveStage_OnEnviroWaveTick                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FCrEnviroWaveSettings&     WaveSettings_OnEnviroWaveTick                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
// float                                   WaveProgress_OnEnviroWaveTick                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HabitatPostProcess_C::OnEnviroWaveTick(EEnviroWave WaveType_OnEnviroWaveTick, EEnviroWaveStage WaveStage_OnEnviroWaveTick, const struct FCrEnviroWaveSettings& WaveSettings_OnEnviroWaveTick, float WaveProgress_OnEnviroWaveTick)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HabitatPostProcess_C", "OnEnviroWaveTick");

	Params::BP_HabitatPostProcess_C_OnEnviroWaveTick Parms{};

	Parms.WaveType_OnEnviroWaveTick = WaveType_OnEnviroWaveTick;
	Parms.WaveStage_OnEnviroWaveTick = WaveStage_OnEnviroWaveTick;
	Parms.WaveSettings_OnEnviroWaveTick = std::move(WaveSettings_OnEnviroWaveTick);
	Parms.WaveProgress_OnEnviroWaveTick = WaveProgress_OnEnviroWaveTick;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_HabitatPostProcess.BP_HabitatPostProcess_C.ExecuteUbergraph_BP_HabitatPostProcess
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_HabitatPostProcess_C::ExecuteUbergraph_BP_HabitatPostProcess(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_HabitatPostProcess_C", "ExecuteUbergraph_BP_HabitatPostProcess");

	Params::BP_HabitatPostProcess_C_ExecuteUbergraph_BP_HabitatPostProcess Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


SDK_NAMESPACE_END
