#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MiningTool

#include "Basic.hpp"

#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_MiningTool.BP_MiningTool_C
// 0x0000 (0x12F0 - 0x12F0)
class UBP_MiningTool_C final : public UCrWeaponItemDataBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_MiningTool_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_MiningTool_C")
	}
	static class UBP_MiningTool_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_MiningTool_C>();
	}
};
DUMPER7_ASSERTS_UBP_MiningTool_C;

SDK_NAMESPACE_END
