#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Melee_Tier3_Actor_AnimNotify_ShowLongAoeAttackWarning

#include "Basic.hpp"

#include "Engine_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Melee_Tier3_Actor_AnimNotify_ShowLongAoeAttackWarning.BP_Melee_Tier3_Actor_AnimNotify_ShowLongAoeAttackWarning_C
// 0x0000 (0x0038 - 0x0038)
class UBP_Melee_Tier3_Actor_AnimNotify_ShowLongAoeAttackWarning_C final : public UAnimNotify
{
public:
	bool Received_Notify(class USkeletalMeshComponent* MeshComp_Received_Notify, class UAnimSequenceBase* Animation_Received_Notify, const struct FAnimNotifyEventReference& EventReference_Received_Notify) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Melee_Tier3_Actor_AnimNotify_ShowLongAoeAttackWarning_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Melee_Tier3_Actor_AnimNotify_ShowLongAoeAttackWarning_C")
	}
	static class UBP_Melee_Tier3_Actor_AnimNotify_ShowLongAoeAttackWarning_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBP_Melee_Tier3_Actor_AnimNotify_ShowLongAoeAttackWarning_C>();
	}
};
DUMPER7_ASSERTS_UBP_Melee_Tier3_Actor_AnimNotify_ShowLongAoeAttackWarning_C;

SDK_NAMESPACE_END
