#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_MechanicalDrillTier2

#include "Basic.hpp"

#include "BP_MechanicalDrillTier2_classes.hpp"
#include "BP_MechanicalDrillTier2_parameters.hpp"


SDK_NAMESPACE_START

// Function BP_MechanicalDrillTier2.BP_MechanicalDrillTier2_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_MechanicalDrillTier2_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MechanicalDrillTier2_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_MechanicalDrillTier2.BP_MechanicalDrillTier2_C.OnResourceDetected
// (Event, Public, BlueprintEvent)
// Parameters:
// TSubclassOf<class UCrItemDataBase>      OreItemClass_OnResourceDetected                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

void ABP_MechanicalDrillTier2_C::OnResourceDetected(TSubclassOf<class UCrItemDataBase> OreItemClass_OnResourceDetected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MechanicalDrillTier2_C", "OnResourceDetected");

	Params::BP_MechanicalDrillTier2_C_OnResourceDetected Parms{};

	Parms.OreItemClass_OnResourceDetected = OreItemClass_OnResourceDetected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MechanicalDrillTier2.BP_MechanicalDrillTier2_C.OnBuildingStateChanged
// (Event, Public, BlueprintEvent)
// Parameters:
// ECrBuildingState                        InState_OnBuildingStateChanged                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MechanicalDrillTier2_C::OnBuildingStateChanged(ECrBuildingState InState_OnBuildingStateChanged)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MechanicalDrillTier2_C", "OnBuildingStateChanged");

	Params::BP_MechanicalDrillTier2_C_OnBuildingStateChanged Parms{};

	Parms.InState_OnBuildingStateChanged = InState_OnBuildingStateChanged;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MechanicalDrillTier2.BP_MechanicalDrillTier2_C.ExecuteUbergraph_BP_MechanicalDrillTier2
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_MechanicalDrillTier2_C::ExecuteUbergraph_BP_MechanicalDrillTier2(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MechanicalDrillTier2_C", "ExecuteUbergraph_BP_MechanicalDrillTier2");

	Params::BP_MechanicalDrillTier2_C_ExecuteUbergraph_BP_MechanicalDrillTier2 Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_MechanicalDrillTier2.BP_MechanicalDrillTier2_C.CustomEvent
// (BlueprintCallable, BlueprintEvent)

void ABP_MechanicalDrillTier2_C::CustomEvent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_MechanicalDrillTier2_C", "CustomEvent");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
