#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Modular_BasePlatformStability

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Modular_BasePlatformStability.BP_Modular_BasePlatformStability_C
// 0x0030 (0x08E8 - 0x08B8)
class ABP_Modular_BasePlatformStability_C final : public ACrCustomBuilding
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x08B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UStaticMeshComponent*                   Connector3;                                        // 0x08C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Connector;                                         // 0x08C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Connector1;                                        // 0x08D0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Connector2;                                        // 0x08D8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UCrInteriorsMapperBoxComponent*         CrInteriorsMapperBox;                              // 0x08E0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_Modular_BasePlatformStability(int32 EntryPoint);
	void ReceiveBeginPlay();
	void UserConstructionScript();

	void GetBuildingMeshes(class UMeshComponent** MainBody, TArray<class UMeshComponent*>* AdditionalMeshes) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Modular_BasePlatformStability_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Modular_BasePlatformStability_C")
	}
	static class ABP_Modular_BasePlatformStability_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Modular_BasePlatformStability_C>();
	}
};
DUMPER7_ASSERTS_ABP_Modular_BasePlatformStability_C;

SDK_NAMESPACE_END
