#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_PlacementHelperReplicatedZipline

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_PlacementHelperReplicatedZipline.BP_PlacementHelperReplicatedZipline_C
// 0x00B0 (0x0A90 - 0x09E0)
class ABP_PlacementHelperReplicatedZipline_C final : public ACrAPHelperActorZipline
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x09E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Beams;                                             // 0x09E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class USplineMeshComponent*>           ConnectingSplines;                                 // 0x09F0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	TArray<class USplineComponent*>               Splines;                                           // 0x0A00(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	struct FColor                                 SplineColor;                                       // 0x0A10(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_A14[0x4];                                      // 0x0A14(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FVector>                        AcceptedLocations;                                 // 0x0A18(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	TArray<struct FVector>                        BlockedLocations;                                  // 0x0A28(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FString                                 BeamEnabledString;                                 // 0x0A38(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   BeamEnabledName;                                   // 0x0A48(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 BeamPositionString;                                // 0x0A50(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   BeamPositionName;                                  // 0x0A60(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 BeamBlockedString;                                 // 0x0A68(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FName                                   BeamBlockedName;                                   // 0x0A78(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         BeamOffsetNumber;                                  // 0x0A80(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void UpdateBlockedBeamLocations();
	void UpdateBeamsLocations();
	void UpdateAcceptedBeamLocations();
	void TurnOnBeams();
	void TurnOffBeams();
	void OnConnectionsModified(const TArray<struct FVector>& NewAcceptedLocations_OnConnectionsModified, const TArray<struct FVector>& NewObstructedLocations_OnConnectionsModified, const TArray<struct FVector>& NewBlockedLocations_OnConnectionsModified);
	void ExecuteUbergraph_BP_PlacementHelperReplicatedZipline(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_PlacementHelperReplicatedZipline_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_PlacementHelperReplicatedZipline_C")
	}
	static class ABP_PlacementHelperReplicatedZipline_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_PlacementHelperReplicatedZipline_C>();
	}
};
DUMPER7_ASSERTS_ABP_PlacementHelperReplicatedZipline_C;

SDK_NAMESPACE_END
