#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Ranged_Tier1_Actor_Character

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_BaseAI_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Ranged_Tier1_Actor_Character.BP_Ranged_Tier1_Actor_Character_C
// 0x0020 (0x0D20 - 0x0D00)
class ABP_Ranged_Tier1_Actor_Character_C final : public ABP_BaseAI_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Ranged_Tier1_Actor_Character_C;  // 0x0D00(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UCrAiRangedAnimationStateSyncComponent* CrAiRangedAnimationStateSync;                      // 0x0D08(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UNiagaraComponent*                      NiagaraEyes;                                       // 0x0D10(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void UserConstructionScript();
	void OnExitActorPool();
	void OnEnterActorPool();
	void OnAiDied(const struct FHitResult& HitResult, const struct FGameplayTag& KillingDamageTag);
	void GetNiagaraEyeSystem(class UNiagaraComponent** NewParam);
	void ExecuteUbergraph_BP_Ranged_Tier1_Actor_Character(int32 EntryPoint);

	void OnMeshVisibilityUpdated(bool bIsMeshHidden) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Ranged_Tier1_Actor_Character_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Ranged_Tier1_Actor_Character_C")
	}
	static class ABP_Ranged_Tier1_Actor_Character_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Ranged_Tier1_Actor_Character_C>();
	}
};
DUMPER7_ASSERTS_ABP_Ranged_Tier1_Actor_Character_C;

SDK_NAMESPACE_END
