#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_SmelterTier2

#include "Basic.hpp"

#include "Chimera_structs.hpp"
#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_SmelterTier2.BP_SmelterTier2_C
// 0x0068 (0x07B8 - 0x0750)
class ABP_SmelterTier2_C final : public ACrCrafter
{
public:
	class UStaticMeshComponent*                   FakeFog_02;                                        // 0x0750(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_DroneRailCap_02;                                // 0x0758(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_DroneEntry_Inlet_02;                            // 0x0760(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_DroneRailCap_01;                                // 0x0768(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   FakeFog_01;                                        // 0x0770(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   SM_DroneEntry_Outlet_01;                           // 0x0778(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   MainMesh;                                          // 0x0780(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        Static;                                            // 0x0788(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAuActorPlacementSocketsComponent*      AuActorPlacementSockets;                           // 0x0790(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	TArray<class UMeshComponent*>                 tab_meshes;                                        // 0x0798(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance, ContainsInstancedReference)
	class ABP_SmelterTier2_C*                     Target;                                            // 0x07A8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	ECrBuildingState                              BuildingState;                                     // 0x07B0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_SmelterTier2_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_SmelterTier2_C")
	}
	static class ABP_SmelterTier2_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_SmelterTier2_C>();
	}
};
DUMPER7_ASSERTS_ABP_SmelterTier2_C;

SDK_NAMESPACE_END
