#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Sulphur_Logic_Large_AbandonedBase

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_Sulphur_Logic_Large_AbandonedBase.BP_Sulphur_Logic_Large_AbandonedBase_C.OnSulphurActivityChanged
// 0x0001 (0x0001 - 0x0000)
struct BP_Sulphur_Logic_Large_AbandonedBase_C_OnSulphurActivityChanged final
{
public:
	bool                                          bActive;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Sulphur_Logic_Large_AbandonedBase_C_OnSulphurActivityChanged;

// Function BP_Sulphur_Logic_Large_AbandonedBase.BP_Sulphur_Logic_Large_AbandonedBase_C.ExecuteUbergraph_BP_Sulphur_Logic_Large_AbandonedBase
// 0x0008 (0x0008 - 0x0000)
struct BP_Sulphur_Logic_Large_AbandonedBase_C_ExecuteUbergraph_BP_Sulphur_Logic_Large_AbandonedBase final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_Event_bActive;                              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BP_Sulphur_Logic_Large_AbandonedBase_C_ExecuteUbergraph_BP_Sulphur_Logic_Large_AbandonedBase;

}

