#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Sulphur_Logic_Large_AbandonedBase

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "BP_Sulphur_Logic_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_Sulphur_Logic_Large_AbandonedBase.BP_Sulphur_Logic_Large_AbandonedBase_C
// 0x0010 (0x0300 - 0x02F0)
class ABP_Sulphur_Logic_Large_AbandonedBase_C final : public ABP_Sulphur_Logic_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_BP_Sulphur_Logic_Large_AbandonedBase_C; // 0x02F0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UGEBoxComponent*                        GEBox;                                             // 0x02F8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveBeginPlay();
	void OnSulphurActivityChanged(bool bActive);
	void ExecuteUbergraph_BP_Sulphur_Logic_Large_AbandonedBase(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_Sulphur_Logic_Large_AbandonedBase_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_Sulphur_Logic_Large_AbandonedBase_C")
	}
	static class ABP_Sulphur_Logic_Large_AbandonedBase_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_Sulphur_Logic_Large_AbandonedBase_C>();
	}
};
DUMPER7_ASSERTS_ABP_Sulphur_Logic_Large_AbandonedBase_C;

SDK_NAMESPACE_END
