#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ViewportSingle

#include "Basic.hpp"

#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BP_ViewportSingle.BP_ViewportSingle_C
// 0x0020 (0x08D8 - 0x08B8)
class ABP_ViewportSingle_C final : public ACrCustomBuilding
{
public:
	class UBoxComponent*                          InteriorMapperOverlapBox;                          // 0x08B8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UChildActorComponent*                   BP_ViewportStencil;                                // 0x08C0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UStaticMeshComponent*                   Glass;                                             // 0x08C8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, NonTransactional, NoDestructor, HasGetValueTypeHash)
	double                                        DoorAlignment;                                     // 0x08D0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void GetBuildingMeshes(class UMeshComponent** MainBody, TArray<class UMeshComponent*>* AdditionalMeshes) const;

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BP_ViewportSingle_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BP_ViewportSingle_C")
	}
	static class ABP_ViewportSingle_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ABP_ViewportSingle_C>();
	}
};
DUMPER7_ASSERTS_ABP_ViewportSingle_C;

SDK_NAMESPACE_END
