#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTDecorator_Exploder_Tier3_IsInCystLocationOrExcludedArea

#include "Basic.hpp"

#include "AIModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BTDecorator_Exploder_Tier3_IsInCystLocationOrExcludedArea.BTDecorator_Exploder_Tier3_IsInCystLocationOrExcludedArea_C
// 0x0008 (0x00A8 - 0x00A0)
class UBTDecorator_Exploder_Tier3_IsInCystLocationOrExcludedArea_C final : public UBTDecorator_BlueprintBase
{
public:
	double                                        Radius;                                            // 0x00A0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	bool PerformConditionCheckAI(class AAIController* OwnerController, class APawn* ControlledPawn);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTDecorator_Exploder_Tier3_IsInCystLocationOrExcludedArea_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTDecorator_Exploder_Tier3_IsInCystLocationOrExcludedArea_C")
	}
	static class UBTDecorator_Exploder_Tier3_IsInCystLocationOrExcludedArea_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTDecorator_Exploder_Tier3_IsInCystLocationOrExcludedArea_C>();
	}
};
DUMPER7_ASSERTS_UBTDecorator_Exploder_Tier3_IsInCystLocationOrExcludedArea_C;

SDK_NAMESPACE_END
