#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTService_EnsureMeshIsVisible

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BTService_EnsureMeshIsVisible.BTService_EnsureMeshIsVisible_C
// 0x0008 (0x00A0 - 0x0098)
class UBTService_EnsureMeshIsVisible_C final : public UBTService_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0098(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ReceiveTickAI(class AAIController* OwnerController, class APawn* ControlledPawn, float DeltaSeconds);
	void ExecuteUbergraph_BTService_EnsureMeshIsVisible(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTService_EnsureMeshIsVisible_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTService_EnsureMeshIsVisible_C")
	}
	static class UBTService_EnsureMeshIsVisible_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTService_EnsureMeshIsVisible_C>();
	}
};
DUMPER7_ASSERTS_UBTService_EnsureMeshIsVisible_C;

SDK_NAMESPACE_END
