#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTT_Exploder_Tier3_Prototype_SpawnCysts

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "AIModule_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass BTT_Exploder_Tier3_Prototype_SpawnCysts.BTT_Exploder_Tier3_Prototype_SpawnCysts_C
// 0x0030 (0x00D8 - 0x00A8)
class UBTT_Exploder_Tier3_Prototype_SpawnCysts_C final : public UBTTask_BlueprintBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x00A8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UClass*                                 CystClass;                                         // 0x00B0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_Exploder_Tier3_Prototype_Actor_Character_C* Character;                                 // 0x00B8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FVector                                SpawnLocation;                                     // 0x00C0(0x0018)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ReceiveExecuteAI(class AAIController* OwnerController_ReceiveExecuteAI, class APawn* ControlledPawn_ReceiveExecuteAI);
	void ExecuteUbergraph_BTT_Exploder_Tier3_Prototype_SpawnCysts(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("BTT_Exploder_Tier3_Prototype_SpawnCysts_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"BTT_Exploder_Tier3_Prototype_SpawnCysts_C")
	}
	static class UBTT_Exploder_Tier3_Prototype_SpawnCysts_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBTT_Exploder_Tier3_Prototype_SpawnCysts_C>();
	}
};
DUMPER7_ASSERTS_UBTT_Exploder_Tier3_Prototype_SpawnCysts_C;

SDK_NAMESPACE_END
