#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BTTask_Exploder_Tier2_Actor_RegisterMovementFailed

#include "Basic.hpp"


SDK_NAMESPACE_START
SDK_PARAM_NAMESPACE_START

// Function BTTask_Exploder_Tier2_Actor_RegisterMovementFailed.BTTask_Exploder_Tier2_Actor_RegisterMovementFailed_C.ReceiveExecuteAI
// 0x0010 (0x0010 - 0x0000)
struct BTTask_Exploder_Tier2_Actor_RegisterMovementFailed_C_ReceiveExecuteAI final
{
public:
	class AAIController*                          OwnerController_ReceiveExecuteAI;                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  ControlledPawn_ReceiveExecuteAI;                   // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BTTask_Exploder_Tier2_Actor_RegisterMovementFailed_C_ReceiveExecuteAI;

// Function BTTask_Exploder_Tier2_Actor_RegisterMovementFailed.BTTask_Exploder_Tier2_Actor_RegisterMovementFailed_C.ExecuteUbergraph_BTTask_Exploder_Tier2_Actor_RegisterMovementFailed
// 0x0040 (0x0040 - 0x0000)
struct BTTask_Exploder_Tier2_Actor_RegisterMovementFailed_C_ExecuteUbergraph_BTTask_Exploder_Tier2_Actor_RegisterMovementFailed final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AAIController*                          K2Node_Event_OwnerController;                      // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  K2Node_Event_ControlledPawn;                       // 0x0010(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class ABP_Exploder_Tier2_Actor_Character_C*   K2Node_DynamicCast_AsBP_Exploder_Tier_2_Actor_Character; // 0x0018(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_GetMovementFailsNum_ReturnValue;          // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_29[0x7];                                       // 0x0029(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_IntToString_ReturnValue;             // 0x0030(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
DUMPER7_ASSERTS_BTTask_Exploder_Tier2_Actor_RegisterMovementFailed_C_ExecuteUbergraph_BTTask_Exploder_Tier2_Actor_RegisterMovementFailed;

SDK_PARAM_NAMESPACE_END
SDK_NAMESPACE_END
