#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_GenericADSZoom

#include "Basic.hpp"

#include "GA_GenericADSZoom_classes.hpp"
#include "GA_GenericADSZoom_parameters.hpp"


SDK_NAMESPACE_START

// Function GA_GenericADSZoom.GA_GenericADSZoom_C.ExecuteUbergraph_GA_GenericADSZoom
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_GenericADSZoom_C::ExecuteUbergraph_GA_GenericADSZoom(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_GenericADSZoom_C", "ExecuteUbergraph_GA_GenericADSZoom");

	Params::GA_GenericADSZoom_C_ExecuteUbergraph_GA_GenericADSZoom Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_GenericADSZoom.GA_GenericADSZoom_C.GetFovCameraModifierForADS
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FAuCameraAdditiveHandle*         Camera_Config                                          (Parm, OutParm, NoDestructor)

void UGA_GenericADSZoom_C::GetFovCameraModifierForADS(struct FAuCameraAdditiveHandle* Camera_Config)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_GenericADSZoom_C", "GetFovCameraModifierForADS");

	Params::GA_GenericADSZoom_C_GetFovCameraModifierForADS Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Camera_Config != nullptr)
		*Camera_Config = std::move(Parms.Camera_Config);
}


// Function GA_GenericADSZoom.GA_GenericADSZoom_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_GenericADSZoom_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_GenericADSZoom_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_GenericADSZoom.GA_GenericADSZoom_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_GenericADSZoom_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_GenericADSZoom_C", "K2_OnEndAbility");

	Params::GA_GenericADSZoom_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_GenericADSZoom.GA_GenericADSZoom_C.PlayADS_ChangeSound
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Enter                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_GenericADSZoom_C::PlayADS_ChangeSound(bool Enter)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_GenericADSZoom_C", "PlayADS_ChangeSound");

	Params::GA_GenericADSZoom_C_PlayADS_ChangeSound Parms{};

	Parms.Enter = Enter;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_GenericADSZoom.GA_GenericADSZoom_C.Removed_B0E889A1483489E37740C08E9097A925
// (BlueprintCallable, BlueprintEvent)

void UGA_GenericADSZoom_C::Removed_B0E889A1483489E37740C08E9097A925()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_GenericADSZoom_C", "Removed_B0E889A1483489E37740C08E9097A925");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_GenericADSZoom.GA_GenericADSZoom_C.Removed_DFB9A8094FFA3F63A36AA4B08C05A0B0
// (BlueprintCallable, BlueprintEvent)

void UGA_GenericADSZoom_C::Removed_DFB9A8094FFA3F63A36AA4B08C05A0B0()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_GenericADSZoom_C", "Removed_DFB9A8094FFA3F63A36AA4B08C05A0B0");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
