#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_InfectionInfiniteDecreaseForce

#include "Basic.hpp"

#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass GE_InfectionInfiniteDecreaseForce.GE_InfectionInfiniteDecreaseForce_C
// 0x0000 (0x0A90 - 0x0A90)
class UGE_InfectionInfiniteDecreaseForce_C final : public UCrGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("GE_InfectionInfiniteDecreaseForce_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"GE_InfectionInfiniteDecreaseForce_C")
	}
	static class UGE_InfectionInfiniteDecreaseForce_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_InfectionInfiniteDecreaseForce_C>();
	}
};
DUMPER7_ASSERTS_UGE_InfectionInfiniteDecreaseForce_C;

SDK_NAMESPACE_END
