#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_KeyCard_FE1_A

#include "Basic.hpp"

#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass I_KeyCard_FE1_A.I_KeyCard_FE1_A_C
// 0x0000 (0x04B0 - 0x04B0)
class UI_KeyCard_FE1_A_C final : public UCrQuestItemDataBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("I_KeyCard_FE1_A_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"I_KeyCard_FE1_A_C")
	}
	static class UI_KeyCard_FE1_A_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UI_KeyCard_FE1_A_C>();
	}
};
DUMPER7_ASSERTS_UI_KeyCard_FE1_A_C;

SDK_NAMESPACE_END
