#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: I_VulpirMeal

#include "Basic.hpp"

#include "Chimera_classes.hpp"


SDK_NAMESPACE_START

// BlueprintGeneratedClass I_VulpirMeal.I_VulpirMeal_C
// 0x0000 (0x0420 - 0x0420)
class UI_VulpirMeal_C final : public UCrEdibleItemBase
{
public:
	static class UClass* StaticClass()
	{
		BP_STATIC_CLASS_IMPL("I_VulpirMeal_C")
	}
	static const class FName& StaticName()
	{
		STATIC_NAME_IMPL(L"I_VulpirMeal_C")
	}
	static class UI_VulpirMeal_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UI_VulpirMeal_C>();
	}
};
DUMPER7_ASSERTS_UI_VulpirMeal_C;

SDK_NAMESPACE_END
