#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PCGPointCreationMethod

#include "Basic.hpp"


SDK_NAMESPACE_START

// UserDefinedEnum PCGPointCreationMethod.PCGPointCreationMethod
// NumValues: 0x0005
enum class EPCGPointCreationMethod : uint8
{
	NewEnumerator0                           = 0,
	NewEnumerator1                           = 1,
	NewEnumerator2                           = 2,
	NewEnumerator3                           = 3,
	PCGPointCreationMethod_MAX               = 4,
};

SDK_NAMESPACE_END
