#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_Sniper_Scope_ScopeOverlay

#include "Basic.hpp"

#include "WBP_Sniper_Scope_ScopeOverlay_classes.hpp"
#include "WBP_Sniper_Scope_ScopeOverlay_parameters.hpp"


SDK_NAMESPACE_START

// Function WBP_Sniper_Scope_ScopeOverlay.WBP_Sniper_Scope_ScopeOverlay_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Sniper_Scope_ScopeOverlay_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Sniper_Scope_ScopeOverlay_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Sniper_Scope_ScopeOverlay.WBP_Sniper_Scope_ScopeOverlay_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWBP_Sniper_Scope_ScopeOverlay_C::Destruct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Sniper_Scope_ScopeOverlay_C", "Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_Sniper_Scope_ScopeOverlay.WBP_Sniper_Scope_ScopeOverlay_C.ExecuteUbergraph_WBP_Sniper_Scope_ScopeOverlay
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Sniper_Scope_ScopeOverlay_C::ExecuteUbergraph_WBP_Sniper_Scope_ScopeOverlay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Sniper_Scope_ScopeOverlay_C", "ExecuteUbergraph_WBP_Sniper_Scope_ScopeOverlay");

	Params::WBP_Sniper_Scope_ScopeOverlay_C_ExecuteUbergraph_WBP_Sniper_Scope_ScopeOverlay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Sniper_Scope_ScopeOverlay.WBP_Sniper_Scope_ScopeOverlay_C.Get_ScopeOverlay_Brush
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// struct FSlateBrush                      ReturnValue                                            (Parm, OutParm, ReturnParm)

struct FSlateBrush UWBP_Sniper_Scope_ScopeOverlay_C::Get_ScopeOverlay_Brush()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Sniper_Scope_ScopeOverlay_C", "Get_ScopeOverlay_Brush");

	Params::WBP_Sniper_Scope_ScopeOverlay_C_Get_ScopeOverlay_Brush Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WBP_Sniper_Scope_ScopeOverlay.WBP_Sniper_Scope_ScopeOverlay_C.OnTagAdded_9D08466543D5D2C4AC0E5AB4CA70AAC6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_Sniper_Scope_ScopeOverlay_C::OnTagAdded_9D08466543D5D2C4AC0E5AB4CA70AAC6(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Sniper_Scope_ScopeOverlay_C", "OnTagAdded_9D08466543D5D2C4AC0E5AB4CA70AAC6");

	Params::WBP_Sniper_Scope_ScopeOverlay_C_OnTagAdded_9D08466543D5D2C4AC0E5AB4CA70AAC6 Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Sniper_Scope_ScopeOverlay.WBP_Sniper_Scope_ScopeOverlay_C.OnTagRemoved_9D08466543D5D2C4AC0E5AB4CA70AAC6
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FGameplayTag&              Tag                                                    (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)

void UWBP_Sniper_Scope_ScopeOverlay_C::OnTagRemoved_9D08466543D5D2C4AC0E5AB4CA70AAC6(const struct FGameplayTag& Tag)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Sniper_Scope_ScopeOverlay_C", "OnTagRemoved_9D08466543D5D2C4AC0E5AB4CA70AAC6");

	Params::WBP_Sniper_Scope_ScopeOverlay_C_OnTagRemoved_9D08466543D5D2C4AC0E5AB4CA70AAC6 Parms{};

	Parms.Tag = std::move(Tag);

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Sniper_Scope_ScopeOverlay.WBP_Sniper_Scope_ScopeOverlay_C.PawnChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class APawn*                            OldPawn                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class APawn*                            NewPawn                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_Sniper_Scope_ScopeOverlay_C::PawnChanged(class APawn* OldPawn, class APawn* NewPawn)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Sniper_Scope_ScopeOverlay_C", "PawnChanged");

	Params::WBP_Sniper_Scope_ScopeOverlay_C_PawnChanged Parms{};

	Parms.OldPawn = OldPawn;
	Parms.NewPawn = NewPawn;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Sniper_Scope_ScopeOverlay.WBP_Sniper_Scope_ScopeOverlay_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Sniper_Scope_ScopeOverlay_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Sniper_Scope_ScopeOverlay_C", "Tick");

	Params::WBP_Sniper_Scope_ScopeOverlay_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Sniper_Scope_ScopeOverlay.WBP_Sniper_Scope_ScopeOverlay_C.UpdateCrosshairSpread
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// double                                  Delta_Seconds                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_Sniper_Scope_ScopeOverlay_C::UpdateCrosshairSpread(double Delta_Seconds)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Sniper_Scope_ScopeOverlay_C", "UpdateCrosshairSpread");

	Params::WBP_Sniper_Scope_ScopeOverlay_C_UpdateCrosshairSpread Parms{};

	Parms.Delta_Seconds = Delta_Seconds;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_Sniper_Scope_ScopeOverlay.WBP_Sniper_Scope_ScopeOverlay_C.UpdateOverlayColors
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UWBP_Sniper_Scope_ScopeOverlay_C::UpdateOverlayColors()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WBP_Sniper_Scope_ScopeOverlay_C", "UpdateOverlayColors");

	UObject::ProcessEvent(Func, nullptr);
}


SDK_NAMESPACE_END
